// SMMC 2023 crosswalk — authored from the official 2023 problem/solution material.
// A/B are East-core; C is supplementary for the East preparation track.
// Problem statements are summarized rather than reproduced.
// t25Targets is authoritative; live 1–162 route positions are resolved from canonical T25 when needed.

export default [
  {
    id: "SMMC-2023-A1",
    year: 2023, session: "A", problem: 1, eastRelevant: true,
    synopsis: "Track the limiting endpoint of a self-similar q-Fibonacci spiral and prove its distance from the centre of the initial square is independent of q.",
    primaryDomain: "S5",
    secondaryTags: ["SEQ", "SERIES", "CX", "COORD"],
    methodTags: ["AUXILIARY-OBJECT", "RECURRENCE-REFORMULATION", "CROSS-DOMAIN", "BOUNDING"],
    t25Targets: ["A2", "A4", "A5", "C1", "G2"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "An official route uses only geometric-series summation and coordinate distance; another uses a linear recurrence in the complex plane. Both sit within T25 foundations."
  },
  {
    id: "SMMC-2023-A2",
    year: 2023, session: "A", problem: 2, eastRelevant: true,
    synopsis: "Count convex functions assembled pointwise from finitely many nonparallel affine functions, optimizing the count over line arrangements.",
    primaryDomain: "S2",
    secondaryTags: ["FUNC", "CONVEX", "CONST"],
    methodTags: ["AUXILIARY-OBJECT", "LEMMA-EXTRACTION", "CONSTRUCTION", "EXTREMAL", "CROSS-DOMAIN"],
    t25Targets: ["F4", "F5", "A3", "C1", "C5"],
    t25Bridges: [],
    overlap: "amber",
    bridgeNeeds: ["Elementary structural facts about one-dimensional convex functions", "Upper envelopes of affine functions and supporting/tangent-line constructions"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "T25 owns inequalities, continuity and optimisation, but not the compact convex-analysis fact pattern used to identify every admissible function as a maximum of selected affine pieces."
  },
  {
    id: "SMMC-2023-A3",
    year: 2023, session: "A", problem: 3, eastRelevant: true,
    synopsis: "Minimize the size of the union of n pairwise non-contained sets having distinct cardinalities, including a sharp inductive construction.",
    primaryDomain: "S2",
    secondaryTags: ["CONST"],
    methodTags: ["BOUNDING", "CONSTRUCTION", "INDUCTION", "EXTREMAL", "CASE-DECOMPOSITION"],
    t25Targets: ["F5", "P2"],
    t25Bridges: ["BR-I"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The proof uses elementary set containment, cardinality bounds and an explicit induction construction; no content beyond T25 plus its existing induction bridge is required."
  },
  {
    id: "SMMC-2023-A4",
    year: 2023, session: "A", problem: 4, eastRelevant: true,
    synopsis: "Determine exactly which initial values make a nonautonomous nonlinear positive recurrence bounded by combining calculus with invariant regions and growth contradiction.",
    primaryDomain: "S3",
    secondaryTags: ["REC", "SEQ", "INEQ"],
    methodTags: ["MONOTONICITY", "INVARIANT", "BOUNDING", "CONTRADICTION", "CASE-DECOMPOSITION"],
    t25Targets: ["A1", "A3", "A5", "C3", "C5"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Differentiation, critical-point analysis, inequalities, sequence boundedness and contradiction are T25-owned; the contest difficulty lies in inventing the right invariant observations."
  },
  {
    id: "SMMC-2023-B1",
    year: 2023, session: "B", problem: 1, eastRelevant: true,
    synopsis: "Find the smallest disc radius that can contain every subset sum of 2023 planar unit vectors after optimally choosing the centre.",
    primaryDomain: "S5",
    secondaryTags: ["VECTOR-GEO", "INEQ"],
    methodTags: ["AUXILIARY-OBJECT", "SYMMETRY", "BOUNDING", "EQUALITY-CASE"],
    t25Targets: ["A3", "G2", "M5"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Choosing the half-total vector as centre and applying the triangle inequality gives the upper bound; the aligned-vector example gives sharpness. No additional content bridge is needed."
  },
  {
    id: "SMMC-2023-B2",
    year: 2023, session: "B", problem: 2, eastRelevant: true,
    synopsis: "Compute the expected rank of the winner of a recursively paired knockout tournament with a fixed upset probability.",
    primaryDomain: "S6",
    secondaryTags: ["REC", "EXPECT"],
    methodTags: ["INDUCTION", "RECURRENCE-REFORMULATION", "CASE-DECOMPOSITION"],
    t25Targets: ["P4", "J1"],
    t25Bridges: ["BR-I"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "One official solution is a direct induction on tournament depth using conditional expectation; expectation and induction are already present in T25."
  },
  {
    id: "SMMC-2023-B3",
    year: 2023, session: "B", problem: 3, eastRelevant: true,
    synopsis: "For three pairwise-transverse n-dimensional subspaces of R^(2n), construct bases whose corresponding triples are linearly dependent.",
    primaryDomain: "S1",
    secondaryTags: ["LA"],
    methodTags: ["CONSTRUCTION", "AUXILIARY-OBJECT", "LEMMA-EXTRACTION"],
    t25Targets: ["M1", "M2"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The first official proof uses only dimensions, direct-sum decomposition, bases and linear independence, all squarely inside T25 linear algebra."
  },
  {
    id: "SMMC-2023-B4",
    year: 2023, session: "B", problem: 4, eastRelevant: true,
    synopsis: "Classify exponent pairs for which two powers of a real number become rational after adding sqrt(n); part (b) admits only partial results in the official solutions.",
    primaryDomain: "S4",
    secondaryTags: ["VAL", "FUNC", "INEQ"],
    methodTags: ["NORMALIZATION", "SYMMETRY", "MONOTONICITY", "CONTRADICTION", "CROSS-DOMAIN"],
    t25Targets: ["F2", "A3", "C3", "C4"],
    t25Bridges: ["BR-N"],
    overlap: "amber",
    bridgeNeeds: ["Conjugation in Q(sqrt(n)) as an elementary quadratic-irrational tool", "2-adic valuation for the partial results in part (b)", "Power-mean/convexity argument for parity cases"],
    assessmentRole: "open-problem",
    classificationConfidence: "high",
    auditNote: "Part (a) is accessible after a small quadratic-irrational bridge using conjugation and logarithmic monotonicity. The official document gives only known partial results for part (b), including a 2-adic valuation argument."
  },
  {
    id: "SMMC-2023-C1",
    year: 2023, session: "C", problem: 1, eastRelevant: false,
    synopsis: "Place three colours in numbered cups under same-colour congruence restrictions and minimize the number of empty cups.",
    primaryDomain: "S4",
    secondaryTags: ["MOD", "GCD"],
    methodTags: ["NORMALIZATION", "CASE-DECOMPOSITION", "BOUNDING"],
    t25Targets: ["F4", "P2"],
    t25Bridges: ["BR-N"],
    overlap: "amber",
    bridgeNeeds: ["Chinese remainder theorem", "Euler totient for a square-free modulus", "Coprime residue-class counting"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Basic congruence language is in BR-N, but the official solution depends centrally on CRT and phi(30), making this a bounded extension of the contest-number-theory bridge."
  },
  {
    id: "SMMC-2023-C2",
    year: 2023, session: "C", problem: 2, eastRelevant: false,
    synopsis: "Determine when a line-arrangement tiling has equal total red and blue area by pairing equal-area regions and isolating the parity obstruction.",
    primaryDomain: "S5",
    secondaryTags: ["COORD"],
    methodTags: ["COLORING", "COORDINATES", "PARITY", "BIJECTION", "CASE-DECOMPOSITION"],
    t25Targets: ["F4", "G2"],
    t25Bridges: ["BR-N"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The solution uses explicit line intersections, equal spacing, elementary area pairing and parity. T25 coordinate geometry plus the parity bridge is sufficient."
  },
  {
    id: "SMMC-2023-C3",
    year: 2023, session: "C", problem: 3, eastRelevant: false,
    synopsis: "Find the sharp additive constant in a universal lower bound for a telescoping product-constrained sum of successive ratios.",
    primaryDomain: "S1",
    secondaryTags: ["INEQ", "ASYM", "INT"],
    methodTags: ["BOUNDING", "EQUALITY-CASE", "CROSS-DOMAIN", "CONSTRUCTION"],
    t25Targets: ["A3", "C1", "C6", "C7"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "AM-GM gives the finite-n optimum and T25 limit/Riemann-sum machinery supplies the sharp limiting constant; an official alternative proof explicitly uses a Riemann integral."
  },
  {
    id: "SMMC-2023-C4",
    year: 2023, session: "C", problem: 4, eastRelevant: false,
    synopsis: "A reverse-chess pursuit game asks for the threshold number of kings that guarantees capture of a noncapturing rook on arbitrarily long boards.",
    primaryDomain: "S2",
    secondaryTags: ["GAME", "CONST"],
    methodTags: ["CONSTRUCTION", "INVARIANT", "BOUNDING", "CASE-DECOMPOSITION"],
    t25Targets: ["F4", "P2", "G2"],
    t25Bridges: [],
    overlap: "amber",
    bridgeNeeds: ["Pursuit/guarding strategy design on a grid", "Barrier and safe-region invariants for adversarial motion"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "No advanced theorem is needed, but the official proof depends on a nontrivial pursuit/guarding construction that is outside ordinary M.Stat training and belongs in the SMMC methods layer."
  }
];
