// SMMC 2022 crosswalk — authored from the official 2022 problem/solution material.
// A/B are East-core; C is supplementary for the East preparation track.
// Problem statements are summarized rather than reproduced.
// t25Targets is authoritative; live 1–162 route positions are resolved from canonical T25 when needed.

export default [
  {
    id: "SMMC-2022-A1",
    year: 2022, session: "A", problem: 1, eastRelevant: true,
    synopsis: "Compare the area of an interior rectangle in a unit square with two surrounding quadrilaterals and compress both inequalities into one polynomial sign condition.",
    primaryDomain: "S5",
    secondaryTags: ["COORD", "INEQ"],
    methodTags: ["SUBSTITUTION", "FACTORIZATION", "CROSS-DOMAIN"],
    t25Targets: ["F2", "A1", "A3", "G2"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Area formulas, algebraic rearrangement and sign equivalence are fully within T25; the challenge is recognizing the shared polynomial condition."
  },
  {
    id: "SMMC-2022-A2",
    year: 2022, session: "A", problem: 2, eastRelevant: true,
    synopsis: "Independently choose n random subsets of a 2^n-element set and find the limiting probability that their union is everything while their intersection is empty.",
    primaryDomain: "S6",
    secondaryTags: ["ASYM"],
    methodTags: ["CASE-DECOMPOSITION", "CROSS-DOMAIN", "BOUNDING"],
    t25Targets: ["P1", "P6", "C1"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The official solution reduces the event to independent membership-bit conditions and a standard exponential limit, both supported by T25 probability and limits."
  },
  {
    id: "SMMC-2022-A3",
    year: 2022, session: "A", problem: 3, eastRelevant: true,
    synopsis: "Use inverse trigonometric functions and an integral-area comparison to prove that a parameterized equation has at least two solutions in the unit interval.",
    primaryDomain: "S3",
    secondaryTags: ["INT", "FUNC", "CONVEX"],
    methodTags: ["AUXILIARY-OBJECT", "CROSS-DOMAIN", "EXISTENCE", "CONVEXITY"],
    t25Targets: ["F5", "G1", "C3", "C4", "C6"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Inverse functions, differentiation/concavity, FTC and IVT are all available in T25; the novelty is the geometric interpretation of the integral and placement of the two crossings."
  },
  {
    id: "SMMC-2022-A4",
    year: 2022, session: "A", problem: 4, eastRelevant: true,
    synopsis: "Prove integrality and a coprimality property of a factorial-normalized product of q^i-1 terms under a restriction on the prime factors of q.",
    primaryDomain: "S4",
    secondaryTags: ["PRIME", "MOD", "VAL"],
    methodTags: ["FACTORIZATION", "BOUNDING", "CROSS-DOMAIN", "LEMMA-EXTRACTION"],
    t25Targets: ["F4", "A2", "P2"],
    t25Bridges: ["BR-N"],
    overlap: "red",
    bridgeNeeds: ["Multiplicative order modulo prime powers", "Euler-totient/unit-group reasoning", "p-adic valuations and Legendre-style factorial valuation bounds", "Valuation comparison in a binomial expansion"],
    assessmentRole: "development",
    classificationConfidence: "high",
    auditNote: "The official elementary-number-theory route is substantially beyond T25/BR-N; an alternative solution is even more advanced, using GL_n over a finite field and Lagrange's theorem."
  },
  {
    id: "SMMC-2022-B1",
    year: 2022, session: "B", problem: 1, eastRelevant: true,
    synopsis: "Classify positive-integer exponent pairs for which two shifted-power functions agree at some positive real input.",
    primaryDomain: "S3",
    secondaryTags: ["FUNC", "INEQ"],
    methodTags: ["NORMALIZATION", "CONVEXITY", "EXISTENCE", "FACTORIZATION"],
    t25Targets: ["F2", "A3", "C1", "C3", "C4", "C5"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "One official route uses convexity plus a sign-change polynomial argument; another uses continuity, endpoint limits and IVT. Both are directly T25-supported."
  },
  {
    id: "SMMC-2022-B2",
    year: 2022, session: "B", problem: 2, eastRelevant: true,
    synopsis: "An even real sextic has all roots on a unique circle in the complex plane; use root symmetries and factorization to prove a coefficient identity.",
    primaryDomain: "S1",
    secondaryTags: ["POLY", "CX", "COORD"],
    methodTags: ["SYMMETRY", "CASE-DECOMPOSITION", "FACTORIZATION", "CROSS-DOMAIN"],
    t25Targets: ["A1", "A4", "G2"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Conjugate and sign-paired roots, circle geometry and coefficient factorization lie inside the T25 algebra/complex/coordinate toolkit."
  },
  {
    id: "SMMC-2022-B3",
    year: 2022, session: "B", problem: 3, eastRelevant: true,
    synopsis: "Analyze a chocolate-cutting impartial game and prove the winning-position classification for a specific large rectangle.",
    primaryDomain: "S2",
    secondaryTags: ["GAME", "REC"],
    methodTags: ["INDUCTION", "INVARIANT", "CASE-DECOMPOSITION", "CONSTRUCTION"],
    t25Targets: ["F4", "A5"],
    t25Bridges: ["BR-I"],
    overlap: "amber",
    bridgeNeeds: ["P/N-position reasoning for impartial games", "Winning-strategy induction and move-to-losing-position logic"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The first official solution is elementary induction once the game-state language and P/N strategy logic are available; full Sprague-Grundy theory is not required."
  },
  {
    id: "SMMC-2022-B4",
    year: 2022, session: "B", problem: 4, eastRelevant: true,
    synopsis: "Two floor-driven integer recurrences must eventually have bounded difference; part (b) asks whether the two sequences must ever be equal.",
    primaryDomain: "S2",
    secondaryTags: ["REC", "FLOOR", "MOD"],
    methodTags: ["INVARIANT", "MONOVARIANT", "BOUNDING", "CASE-DECOMPOSITION", "AUXILIARY-OBJECT"],
    t25Targets: ["F4", "A3", "A5"],
    t25Bridges: ["BR-I", "BR-N"],
    overlap: "amber",
    bridgeNeeds: ["Attracting invariant regions for a discrete map", "Difference-variable trapping and refinement by residue classes", "Contest-level deterministic discrete-dynamics reasoning"],
    assessmentRole: "open-problem",
    classificationConfidence: "high",
    auditNote: "Part (a) uses elementary inequalities, floors and residues but requires a dedicated invariant-region method. The official document supplies only a solution to part (a) and discusses part (b) as unresolved."
  },
  {
    id: "SMMC-2022-C1",
    year: 2022, session: "C", problem: 1, eastRelevant: false,
    synopsis: "Maximize the minimum of three positive expressions in two variables and prove the sharp value.",
    primaryDomain: "S1",
    secondaryTags: ["INEQ", "CONVEX"],
    methodTags: ["NORMALIZATION", "CASE-DECOMPOSITION", "BOUNDING", "OPTIMIZATION"],
    t25Targets: ["A3", "C5"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The official solutions use elementary case reduction, monotonicity and AM-GM-style bounds; all needed mathematical content is T25-owned."
  },
  {
    id: "SMMC-2022-C2",
    year: 2022, session: "C", problem: 2, eastRelevant: false,
    synopsis: "Decide convergence of a positive series whose exponent depends on the ceiling of sin n by extracting a divergent harmonic-scale subseries.",
    primaryDomain: "S3",
    secondaryTags: ["SERIES", "CEIL"],
    methodTags: ["CONSTRUCTION", "BOUNDING", "CASE-DECOMPOSITION"],
    t25Targets: ["A2", "A5", "G1"],
    t25Bridges: [],
    overlap: "red",
    bridgeNeeds: ["Positive-series comparison tests", "Subseries divergence arguments", "Harmonic-series benchmark and block comparison"],
    assessmentRole: "development",
    classificationConfidence: "high",
    auditNote: "This independently confirms the infinite-series gap already seen in 2019: T25 does not teach the general comparison/subseries machinery used by the official solutions."
  },
  {
    id: "SMMC-2022-C3",
    year: 2022, session: "C", problem: 3, eastRelevant: false,
    synopsis: "For a symmetric random walk, compare the probability of landing in a residue class modulo five after 2022 steps with one fifth.",
    primaryDomain: "S6",
    secondaryTags: ["RANDOM-WALK", "REC", "MOD"],
    methodTags: ["RECURRENCE-REFORMULATION", "INDUCTION", "SYMMETRY", "BOUNDING"],
    t25Targets: ["P5", "J1", "J2", "A5"],
    t25Bridges: ["BR-I"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The first official solution needs only residue-state recurrences, symmetry and induction; generating functions and roots of unity are optional alternative routes."
  },
  {
    id: "SMMC-2022-C4",
    year: 2022, session: "C", problem: 4, eastRelevant: false,
    synopsis: "An iid geometric-tailed integer stream stops at its first repeat; derive the exact distribution of the stopping time.",
    primaryDomain: "S6",
    secondaryTags: ["RANDOM-PROCESS", "REC"],
    methodTags: ["BIJECTION", "RECURRENCE-REFORMULATION", "FACTORIZATION", "CONSTRUCTION"],
    t25Targets: ["A2", "P1", "P2", "D2"],
    t25Bridges: ["BR-I"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The proof uses positive geometric weights, ordered distinct tuples, a shift bijection and a recurrence for the all-distinct probability; these are supported by T25's finite counting and geometric-law foundations."
  }
];
