// SMMC 2021 crosswalk — authored from the official 2021 problem/solution material.
// Problem statements are summarized rather than reproduced.
// t25Targets is authoritative; live 1–162 route positions are resolved from canonical T25 when needed.

export default [
  {
    id: "SMMC-2021-A1",
    year: 2021, session: "A", problem: 1, eastRelevant: true,
    synopsis: "A parabola must meet six coefficient-permuted lines in at most one point each; determine the sharp range of a coefficient ratio.",
    primaryDomain: "S1",
    secondaryTags: ["POLY", "COORD", "INEQ"],
    methodTags: ["NORMALIZATION", "FACTORIZATION", "BOUNDING", "EQUALITY-CASE"],
    t25Targets: ["F2", "A1", "A3", "G2"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Scaling, polynomial intersections, discriminant/sign reasoning and endpoint verification are all directly supported by T25."
  },
  {
    id: "SMMC-2021-A2",
    year: 2021, session: "A", problem: 2, eastRelevant: true,
    synopsis: "A gcd-driven integer recurrence; prove exactly when the multiplicative step equals n by tracking prime divisibility through the sequence.",
    primaryDomain: "S4",
    secondaryTags: ["PRIME", "GCD", "REC"],
    methodTags: ["INDUCTION", "INVARIANT", "CASE-DECOMPOSITION", "LEMMA-EXTRACTION"],
    t25Targets: ["F4", "A5"],
    t25Bridges: ["BR-I", "BR-N"],
    overlap: "amber",
    bridgeNeeds: ["Prime-divisibility invariants under a gcd recurrence", "Elementary gcd/prime-factor reasoning beyond parity"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "T25 supplies recurrence and induction discipline, but the invariant itself depends on genuine elementary number-theory fluency."
  },
  {
    id: "SMMC-2021-A3",
    year: 2021, session: "A", problem: 3, eastRelevant: true,
    synopsis: "Classify all determinants of a huge sparse zero-one matrix by reducing rows and interpreting the remaining incidence pattern as a union of cycles.",
    primaryDomain: "S1",
    secondaryTags: ["LA", "GRAPH"],
    methodTags: ["GRAPH-REFORMULATION", "FACTORIZATION", "PARITY", "CONSTRUCTION", "BOUNDING"],
    t25Targets: ["F4", "M2", "M3", "P2"],
    t25Bridges: [],
    overlap: "amber",
    bridgeNeeds: ["2-regular finite graphs decompose into cycles", "Matrix-to-incidence-graph translation and block decomposition by components"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Determinant reduction and counting are T25-owned; only a compact graph bridge is needed to expose the cycle-block structure used by the official solution."
  },
  {
    id: "SMMC-2021-A4",
    year: 2021, session: "A", problem: 4, eastRelevant: true,
    synopsis: "Analyze a floor-defined multiplicative recurrence, prove a normalized limit exists, and determine the exact range of that limit over all positive parameters.",
    primaryDomain: "S3",
    secondaryTags: ["SEQ", "REC", "FLOOR", "ASYM"],
    methodTags: ["MONOTONICITY", "INDUCTION", "BOUNDING", "EXISTENCE", "AUXILIARY-OBJECT"],
    t25Targets: ["A2", "A5", "C1", "C4"],
    t25Bridges: [],
    overlap: "red",
    bridgeNeeds: ["Nested compact-set / infimum-supremum existence arguments", "Right-continuity and one-sided limsup/liminf control for parameter-dependent limits", "Floor-recurrence parameter analysis beyond ordinary sequence convergence"],
    assessmentRole: "development",
    classificationConfidence: "high",
    auditNote: "Part (a) is T25-friendly monotone convergence, but the full range characterization uses substantially deeper real-analysis structure than current T25 owns."
  },
  {
    id: "SMMC-2021-B1",
    year: 2021, session: "B", problem: 1, eastRelevant: true,
    synopsis: "Choose two entries of the zero matrix uniformly, turn them to one, and compute the probability that the square of the resulting matrix is zero.",
    primaryDomain: "S6",
    secondaryTags: ["LA"],
    methodTags: ["CASE-DECOMPOSITION", "BIJECTION", "CROSS-DOMAIN"],
    t25Targets: ["M0", "P1", "P2"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Matrix multiplication plus ordered/unordered finite counting is directly within T25; the official solution even supplies both a direct count and a bijective route."
  },
  {
    id: "SMMC-2021-B2",
    year: 2021, session: "B", problem: 2, eastRelevant: true,
    synopsis: "Rounds toggle exactly 1,2,... switches; determine for which numbers of lamps one can finish a round with every lamp on.",
    primaryDomain: "S2",
    secondaryTags: ["GAME", "CONST"],
    methodTags: ["CONSTRUCTION", "INDUCTION", "PARITY", "INVARIANT", "CASE-DECOMPOSITION"],
    t25Targets: ["F4", "A2", "P2"],
    t25Bridges: ["BR-I", "BR-N"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The main burden is inventive construction; induction and parity are already supplied by T25 plus its existing bridges, so no new mathematical content is required."
  },
  {
    id: "SMMC-2021-B3",
    year: 2021, session: "B", problem: 3, eastRelevant: true,
    synopsis: "Classify Riemann-integrable functions equal to every symmetric local average over radii 1/n; prove that only affine functions work.",
    primaryDomain: "S3",
    secondaryTags: ["FE", "FUNC", "INT"],
    methodTags: ["LEMMA-EXTRACTION", "CONTRADICTION", "EXTREMAL", "CROSS-DOMAIN", "AUXILIARY-OBJECT"],
    t25Targets: ["F4", "C1", "C3", "C4", "C6"],
    t25Bridges: [],
    overlap: "amber",
    bridgeNeeds: ["Basic consequences of Riemann integrability such as boundedness on compact intervals", "Regularity bootstrapping from moving-average identities", "Compact-interval extremum reasoning or an equivalent dense-set integral argument"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "T25 owns FTC, MVT and definite integration, but the official routes need a small real-analysis bridge connecting Riemann integrability, boundedness, continuity and the averaging identity."
  },
  {
    id: "SMMC-2021-B4",
    year: 2021, session: "B", problem: 4, eastRelevant: true,
    synopsis: "Open polynomial-derivative common-root problem; prove the prime-degree rational case collapses to a pure power, then ask for all degrees.",
    primaryDomain: "S1",
    secondaryTags: ["POLY", "MOD", "PRIME", "VAL"],
    methodTags: ["NORMALIZATION", "FACTORIZATION", "DESCENT", "CROSS-DOMAIN"],
    t25Targets: ["F4", "A1", "A3", "C3", "P2"],
    t25Bridges: ["BR-N"],
    overlap: "amber",
    bridgeNeeds: ["Clearing denominators and primitive-integer normalization", "Prime divisibility of interior binomial coefficients", "Coefficient extraction from shifted polynomials and reduction modulo a prime"],
    assessmentRole: "open-problem",
    classificationConfidence: "high",
    auditNote: "The general Casas-Alvero classification is open, but the five-point prime-degree part uses bounded polynomial and modular-number-theory ideas rather than graduate algebra, so it is AMBER rather than RED."
  }
];
