// SMMC 2020 crosswalk — authored from the official 2020 problem/solution material.
// Problem statements are summarized rather than reproduced.
// t25Targets is authoritative; live 1–162 route positions are resolved from canonical T25 when needed.

export default [
  {
    id: "SMMC-2020-A1",
    year: 2020, session: "A", problem: 1, eastRelevant: true,
    synopsis: "A 2-regular geometric graph on 1001 planar points; prove no line can cross every chosen segment in its interior.",
    primaryDomain: "S2",
    secondaryTags: ["GRAPH", "EUCLID"],
    methodTags: ["PARITY", "COLORING", "CONTRADICTION", "GRAPH-REFORMULATION"],
    t25Targets: ["F4", "P2", "G2"],
    t25Bridges: ["BR-N"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "One official solution needs only side-of-line colouring, parity and a short contradiction; T25 plus the existing integer/parity bridge supplies the prerequisite mathematics."
  },
  {
    id: "SMMC-2020-A2",
    year: 2020, session: "A", problem: 2, eastRelevant: true,
    synopsis: "Repeated pile-merging operation on cards; count all distinct final permutations obtainable from the ordered deck.",
    primaryDomain: "S2",
    secondaryTags: ["REC", "CONST"],
    methodTags: ["INDUCTION", "BIJECTION", "RECURRENCE-REFORMULATION", "LEMMA-EXTRACTION"],
    t25Targets: ["F4", "A5", "P2"],
    t25Bridges: ["BR-I"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The official routes use induction, a recoverability lemma and either a recurrence or subset encoding; these are fair unfamiliar transfers once T25 counting and induction support are owned."
  },
  {
    id: "SMMC-2020-A3",
    year: 2020, session: "A", problem: 3, eastRelevant: true,
    synopsis: "Determine the exact range of a positive infinite series built from successive terms of an increasing real sequence starting at one.",
    primaryDomain: "S3",
    secondaryTags: ["SEQ", "SERIES", "INEQ", "ASYM"],
    methodTags: ["CONSTRUCTION", "NORMALIZATION", "BOUNDING", "OPTIMIZATION", "CONVEXITY"],
    t25Targets: ["A2", "A3", "A5", "C5"],
    t25Bridges: [],
    overlap: "amber",
    bridgeNeeds: ["Infimum-based self-similar lower-bound reasoning for a positive series", "Careful passage from finite lower bounds to an infinite positive sum"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "T25 owns geometric sums, AM-GM, sequence limits and one-variable optimisation, but the official lower-bound routes use a compact amount of series/infimum machinery not explicitly taught by the core."
  },
  {
    id: "SMMC-2020-A4",
    year: 2020, session: "A", problem: 4, eastRelevant: true,
    synopsis: "Show that five points in three-space with equal consecutive sides and equal consecutive angles must lie in a plane.",
    primaryDomain: "S5",
    secondaryTags: ["VECTOR-GEO", "LA", "CX"],
    methodTags: ["SYMMETRY", "AUXILIARY-OBJECT", "CROSS-DOMAIN", "LEMMA-EXTRACTION"],
    t25Targets: ["A4", "G2", "M1", "M2", "M4", "M5"],
    t25Bridges: [],
    overlap: "amber",
    bridgeNeeds: ["Gram-matrix viewpoint for vectors", "Recognition/use of a 5-by-5 circulant matrix from roots of unity"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Although the surface is spatial geometry, one official solution reduces the problem to Gram structure, fifth roots of unity, eigenvectors and rank-nullity, making most prerequisites already T25-owned."
  },
  {
    id: "SMMC-2020-B1",
    year: 2020, session: "B", problem: 1, eastRelevant: true,
    synopsis: "For rank-three 5-by-5 real matrices, maximize and minimize the number of nonempty column subsets that are linearly independent.",
    primaryDomain: "S1",
    secondaryTags: ["LA"],
    methodTags: ["BOUNDING", "CONSTRUCTION", "EXTREMAL"],
    t25Targets: ["M1", "M2", "P2"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Rank, basis size, linear independence and elementary subset counting are all directly supported by current T25."
  },
  {
    id: "SMMC-2020-B2",
    year: 2020, session: "B", problem: 2, eastRelevant: true,
    synopsis: "For sums of k unit fractions, prove that the resulting set contains no infinite strictly increasing sequence.",
    primaryDomain: "S2",
    secondaryTags: ["SEQ"],
    methodTags: ["INDUCTION", "PIGEONHOLE", "CONTRADICTION", "SUBSTITUTION"],
    t25Targets: ["F4", "A5"],
    t25Bridges: ["BR-I"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The shortest official route uses induction on k, finite pigeonhole reasoning and subsequence/order arguments; these are fair after T25 sequence work plus the existing induction bridge."
  },
  {
    id: "SMMC-2020-B3",
    year: 2020, session: "B", problem: 3, eastRelevant: true,
    synopsis: "Construct a pursuit strategy in the nonnegative quadrant proving a faster cat catches a continuously moving mouse by time one.",
    primaryDomain: "S5",
    secondaryTags: ["GAME", "VECTOR-GEO", "INT"],
    methodTags: ["CONSTRUCTION", "AUXILIARY-OBJECT", "BOUNDING", "EXISTENCE", "CASE-DECOMPOSITION"],
    t25Targets: ["C1", "C3", "C4", "C6", "F4"],
    t25Bridges: [],
    overlap: "amber",
    bridgeNeeds: ["Piecewise velocity-strategy design for planar pursuit", "First-hitting-time reasoning for continuous trajectories"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "IVT, differentiation, integration and norm inequalities are T25-owned; the missing piece is the control/pursuit construction rather than a large new mathematical subject."
  },
  {
    id: "SMMC-2020-B4",
    year: 2020, session: "B", problem: 4, eastRelevant: true,
    synopsis: "Open regular-polygon difference-set problem; prove the prime case using a finite-field/projective-plane construction, then characterize all possible n.",
    primaryDomain: "S1",
    secondaryTags: ["FF", "MOD", "PROJECTIVE-GEO"],
    methodTags: ["CONSTRUCTION", "CROSS-DOMAIN", "AUXILIARY-OBJECT", "BIJECTION"],
    t25Targets: ["A4", "M1", "P2"],
    t25Bridges: ["BR-N"],
    overlap: "red",
    bridgeNeeds: ["Finite-field extension basics and cyclic multiplicative groups", "Projective-plane/projective-line construction over a finite field", "Difference-set formulation and uniqueness of nonzero differences", "Research-style partial-progress discipline for the open classification"],
    assessmentRole: "open-problem",
    classificationConfidence: "high",
    auditNote: "Part (a) explicitly invokes finite-field and projective-geometry facts from advanced undergraduate algebra; part (b) is open, so this is a genuine specialist extension rather than an M.Stat transfer item."
  }
];
