// SMMC 2025 crosswalk — audited from the official 2025 SMMC solutions on simonmarais.org.
// A/B are East-core; C is supplementary for the East preparation track.
// Problem statements are summarized rather than reproduced.
// t25Targets is authoritative; live 1–162 route positions are resolved from canonical T25 when needed.

export default [
  {
    id: "SMMC-2025-A1",
    year: 2025, session: "A", problem: 1, eastRelevant: true,
    synopsis: "Decide whether min(x,x^2) on the nonnegative reals can be represented as the maximum of finitely many nonnegative polynomials.",
    primaryDomain: "S1",
    secondaryTags: ["POLY", "FUNC", "ASYM"],
    methodTags: ["CONTRADICTION", "PIGEONHOLE", "ASYMPTOTIC-COMPARISON"],
    t25Targets: ["A1", "F4", "C1"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "One official proof uses only polynomial identity from infinitely many matching integer values; another compares lowest/highest polynomial powers near zero and infinity."
  },
  {
    id: "SMMC-2025-A2",
    year: 2025, session: "A", problem: 2, eastRelevant: true,
    synopsis: "For matrices over Z/pZ, determine the average number of nonzero eigenvectors across all n-by-n matrices.",
    primaryDomain: "S1",
    secondaryTags: ["LA", "FF"],
    methodTags: ["DOUBLE-COUNTING", "BIJECTION", "AUXILIARY-OBJECT"],
    t25Targets: ["M1", "M2", "M4", "P2"],
    t25Bridges: ["BR-N"],
    overlap: "amber",
    bridgeNeeds: ["Vector spaces and matrices over the finite field F_p rather than R", "Finite-field cardinality counting for affine/kernel fibers"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The linear-algebra argument is directly T25-shaped, but the field change to F_p and its counting conventions need a compact finite-field bridge."
  },
  {
    id: "SMMC-2025-A3",
    year: 2025, session: "A", problem: 3, eastRelevant: true,
    synopsis: "Entries of a large power of a polynomial 2-by-2 matrix define two degree-2025 polynomials; prove all roots are real, simple and strictly interlacing.",
    primaryDomain: "S1",
    secondaryTags: ["LA", "POLY", "CX"],
    methodTags: ["SUBSTITUTION", "AUXILIARY-OBJECT", "INDUCTION", "MONOTONICITY"],
    t25Targets: ["M4", "A1", "A4", "G1", "C4"],
    t25Bridges: ["BR-I"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The first official route diagonalizes the 2-by-2 matrix, parametrizes roots by roots of unity/cosines and uses cosine monotonicity; all prerequisites exist in T25."
  },
  {
    id: "SMMC-2025-A4",
    year: 2025, session: "A", problem: 4, eastRelevant: true,
    synopsis: "A finite-dimensional space of smooth real functions is closed under dilation x to 2x; prove every function in the space is a polynomial.",
    primaryDomain: "S1",
    secondaryTags: ["LA", "FUNC", "ASYM"],
    methodTags: ["AUXILIARY-OBJECT", "RECURRENCE-REFORMULATION", "CROSS-DOMAIN", "BOUNDING"],
    t25Targets: ["M1", "M4", "A5", "C1", "C3"],
    t25Bridges: [],
    overlap: "red",
    bridgeNeeds: ["Linear operators on finite-dimensional function spaces", "Complexification/eigenvalue decomposition or equivalent operator structure", "Exponential-polynomial recurrence sequences", "Compact-torus/subsequence argument controlling oscillatory exponentials", "Bootstrapping high derivatives to vanish identically"],
    assessmentRole: "development",
    classificationConfidence: "high",
    auditNote: "This is a genuine advanced bridge: T25 linear algebra and calculus supply pieces, but the official proof uses operator/spectral and compactness ideas not present in the core."
  },
  {
    id: "SMMC-2025-B1",
    year: 2025, session: "B", problem: 1, eastRelevant: true,
    synopsis: "Classify n for which every interval of n consecutive integers admits a divisibility-compatible assignment from 1 through n with a collision restriction on non-coprime inputs.",
    primaryDomain: "S4",
    secondaryTags: ["GCD", "MOD", "CONST"],
    methodTags: ["CONSTRUCTION", "CASE-DECOMPOSITION", "PIGEONHOLE", "BOUNDING"],
    t25Targets: ["F4", "P2"],
    t25Bridges: ["BR-N"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The official proof is elementary divisibility/construction plus interval obstructions; BR-N supplies the needed arithmetic language."
  },
  {
    id: "SMMC-2025-B2",
    year: 2025, session: "B", problem: 2, eastRelevant: true,
    synopsis: "Represent the interior of any convex quadrilateral with no parallel sides as the Minkowski sum of the interiors of two triangles.",
    primaryDomain: "S5",
    secondaryTags: ["CONVEX-GEO", "COORD"],
    methodTags: ["CONSTRUCTION", "AUXILIARY-OBJECT", "COORDINATES", "CROSS-DOMAIN"],
    t25Targets: ["G2", "A3"],
    t25Bridges: [],
    overlap: "amber",
    bridgeNeeds: ["Minkowski sums of planar sets", "Elementary convex-hull reasoning for polygons", "Affine/parallel-line construction showing the resulting sum has the required four vertices"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Coordinate geometry is T25-owned, but Minkowski-sum/convex-polygon language and the structural construction are not."
  },
  {
    id: "SMMC-2025-B3",
    year: 2025, session: "B", problem: 3, eastRelevant: true,
    synopsis: "A complex matrix built from distinct z_j and nth roots of unity has zero determinant; prove the product of the z_j equals one.",
    primaryDomain: "S1",
    secondaryTags: ["LA", "CX", "POLY"],
    methodTags: ["FACTORIZATION", "SYMMETRY", "AUXILIARY-OBJECT", "CROSS-DOMAIN"],
    t25Targets: ["M3", "A1", "A4", "P2"],
    t25Bridges: [],
    overlap: "amber",
    bridgeNeeds: ["Vandermonde determinant/factor structure", "Determinant viewed as a multivariate alternating polynomial", "Root-of-unity coefficient comparison at contest depth"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "T25 supplies determinants, complex numbers and polynomials, but the official proof needs a compact Vandermonde/alternating-polynomial bridge."
  },
  {
    id: "SMMC-2025-B4",
    year: 2025, session: "B", problem: 4, eastRelevant: true,
    synopsis: "Solve a cubic geometric-sum perfect-power Diophantine equation, then ask for the complete higher-degree geometric-sum perfect-power classification.",
    primaryDomain: "S4",
    secondaryTags: ["DIO", "VAL", "CX", "PRIME"],
    methodTags: ["FACTORIZATION", "DESCENT", "BOUNDING", "CROSS-DOMAIN"],
    t25Targets: ["A1", "A4", "F4"],
    t25Bridges: ["BR-N"],
    overlap: "red",
    bridgeNeeds: ["Gaussian integers and unique factorization", "Ideal/element divisibility and units in Z[i] at elementary contest depth", "p-adic/Gaussian valuation arguments", "Perfect-power Diophantine bounding"],
    assessmentRole: "open-problem",
    classificationConfidence: "high",
    auditNote: "Part 1 is already far beyond T25/BR-N and uses Gaussian-integer factorization; the official solutions explicitly identify part 2 as the unsolved Nagell-Ljunggren equation."
  },
  {
    id: "SMMC-2025-C1",
    year: 2025, session: "C", problem: 1, eastRelevant: false,
    synopsis: "A frog makes odd-length north/east jumps; determine the minimum possible distance from the start after n jumps.",
    primaryDomain: "S5",
    secondaryTags: ["CONST", "VECTOR-GEO"],
    methodTags: ["CONSTRUCTION", "PARITY", "INDUCTION", "OPTIMIZATION"],
    t25Targets: ["A2", "A3", "G2", "P2"],
    t25Bridges: ["BR-I", "BR-N"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The problem reduces to partitioning odd integers into two sums as evenly as possible, with an explicit inductive construction."
  },
  {
    id: "SMMC-2025-C2",
    year: 2025, session: "C", problem: 2, eastRelevant: false,
    synopsis: "For a two-parameter quartic with integer coefficients, maximize the number of rational roots.",
    primaryDomain: "S1",
    secondaryTags: ["POLY", "VAL"],
    methodTags: ["FACTORIZATION", "PARITY", "CONTRADICTION", "CASE-DECOMPOSITION"],
    t25Targets: ["A1", "F2", "F4"],
    t25Bridges: ["BR-N"],
    overlap: "amber",
    bridgeNeeds: ["Rational-root theorem / primitive integer factorization at contest depth", "Gauss-lemma-style reduction from rational quadratic factors to integer factors"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The official primary solution can avoid the advanced Newton-polygon alternative; only a bounded rational-root/integer-factorization bridge is needed."
  },
  {
    id: "SMMC-2025-C3",
    year: 2025, session: "C", problem: 3, eastRelevant: false,
    synopsis: "Functions built from x,y, addition, subtraction and absolute value are called angelic; decide whether max(x,y) can be represented in this language.",
    primaryDomain: "S1",
    secondaryTags: ["FUNC", "MOD"],
    methodTags: ["INDUCTION", "PARITY", "CONTRADICTION", "NORMALIZATION"],
    t25Targets: ["F4", "F5"],
    t25Bridges: ["BR-N", "BR-I"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "An official solution reduces every allowed expression modulo two to one of four linear forms, giving an elementary parity contradiction."
  },
  {
    id: "SMMC-2025-C4",
    year: 2025, session: "C", problem: 4, eastRelevant: false,
    synopsis: "Given convex f,g,h with f+g below h, split h into two convex functions separately dominating f and g.",
    primaryDomain: "S3",
    secondaryTags: ["CONVEX", "FUNC", "CONVEX-GEO"],
    methodTags: ["AUXILIARY-OBJECT", "CONSTRUCTION", "CONVEXITY", "CASE-DECOMPOSITION"],
    t25Targets: ["A3", "C5", "F5"],
    t25Bridges: [],
    overlap: "red",
    bridgeNeeds: ["Convex envelope and epigraph/convex-hull construction", "Supporting chord structure of one-dimensional convex envelopes", "Proof that subtracting the envelope preserves convexity in the required decomposition"],
    assessmentRole: "development",
    classificationConfidence: "high",
    auditNote: "The official proof is genuinely convex-analytic rather than an ordinary inequality exercise; T25 optimization does not supply convex envelopes or epigraph hulls."
  }
];
