// SMMC 2024 crosswalk — audited from the official 2024 SMMC solutions on simonmarais.org.
// A/B are East-core; C is supplementary for the East preparation track.
// Problem statements are summarized rather than reproduced.
// t25Targets is authoritative; live 1–162 route positions are resolved from canonical T25 when needed.

export default [
  {
    id: "SMMC-2024-A1",
    year: 2024, session: "A", problem: 1, eastRelevant: true,
    synopsis: "Three real numbers above one satisfy a cyclic system coupling each number with the floor of another; prove all three numbers are equal.",
    primaryDomain: "S1",
    secondaryTags: ["FLOOR", "INEQ"],
    methodTags: ["SYMMETRY", "CASE-DECOMPOSITION", "BOUNDING"],
    t25Targets: ["F2", "A3"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The shortest official solution uses cyclic symmetry, order comparison and elementary floor inequalities only."
  },
  {
    id: "SMMC-2024-A2",
    year: 2024, session: "A", problem: 2, eastRelevant: true,
    synopsis: "Partition initial integer intervals into pairs whose sums are powers of three, characterize all feasible n, and count those up to 2024.",
    primaryDomain: "S2",
    secondaryTags: ["CONST", "REC", "MOD"],
    methodTags: ["INDUCTION", "CONSTRUCTION", "RECURRENCE-REFORMULATION", "LEMMA-EXTRACTION"],
    t25Targets: ["F4", "P2", "A5"],
    t25Bridges: ["BR-I", "BR-N"],
    overlap: "amber",
    bridgeNeeds: ["Base-three representation as a contest encoding", "Recursive forced-pair decomposition of an initial interval"],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "T25 supplies induction, finite counting and basic integer reasoning, but the ternary representation/recursive pairing structure is a bounded discrete bridge."
  },
  {
    id: "SMMC-2024-A3",
    year: 2024, session: "A", problem: 3, eastRelevant: true,
    synopsis: "Analyze a family of rational sequences indexed by integer pairs, determine an eventual inequality threshold, and maximize the least valid threshold.",
    primaryDomain: "S3",
    secondaryTags: ["SEQ", "FLOOR", "INEQ"],
    methodTags: ["MONOTONICITY", "NORMALIZATION", "CASE-DECOMPOSITION", "BOUNDING"],
    t25Targets: ["A3", "A5", "F4"],
    t25Bridges: ["BR-N"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The official solution uses monotonicity, limits, floors, the division algorithm and elementary inequality solving; T25 plus BR-N is sufficient."
  },
  {
    id: "SMMC-2024-A4",
    year: 2024, session: "A", problem: 4, eastRelevant: true,
    synopsis: "A random increasing integer sequence uses a uniformly chosen increment from 1 through d at step d; determine the probability it contains infinitely many primes.",
    primaryDomain: "S6",
    secondaryTags: ["RANDOM-PROCESS", "PRIME", "SERIES"],
    methodTags: ["CONDITIONING", "BOUNDING", "AUXILIARY-OBJECT", "CROSS-DOMAIN"],
    t25Targets: ["P4", "P5", "A5", "J1"],
    t25Bridges: ["BR-N"],
    overlap: "red",
    bridgeNeeds: ["Divergence of the sum of reciprocals of the primes", "Infinite-product implication from a divergent reciprocal sum", "Conditional avoidance argument over an infinite sequence of prime targets"],
    assessmentRole: "development",
    classificationConfidence: "high",
    auditNote: "The stochastic setup is T25-friendly, but the official completion depends centrally on a genuine analytic-number-theory theorem outside T25 and on an infinite avoidance/product argument."
  },
  {
    id: "SMMC-2024-B1",
    year: 2024, session: "B", problem: 1, eastRelevant: true,
    synopsis: "Adaptive two-box queries must identify two hidden coin boxes among six; determine the minimum worst-case number of guesses.",
    primaryDomain: "S2",
    secondaryTags: ["GAME", "CONST"],
    methodTags: ["CONSTRUCTION", "CASE-DECOMPOSITION", "BOUNDING", "PIGEONHOLE"],
    t25Targets: ["P2", "F4"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The upper strategy and lower information-state count are elementary finite combinatorics; no new mathematical content is required."
  },
  {
    id: "SMMC-2024-B2",
    year: 2024, session: "B", problem: 2, eastRelevant: true,
    synopsis: "Classify continuous functions on R except one point satisfying a multiplicative functional equation involving x and x squared.",
    primaryDomain: "S3",
    secondaryTags: ["FE", "FUNC", "SEQ"],
    methodTags: ["SUBSTITUTION", "INVARIANT", "MONOTONICITY", "LEMMA-EXTRACTION"],
    t25Targets: ["F5", "A5", "C1"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "After multiplying by x-1, the equation becomes an invariance under squaring; continuity and elementary convergent sequences complete the official proof."
  },
  {
    id: "SMMC-2024-B3",
    year: 2024, session: "B", problem: 3, eastRelevant: true,
    synopsis: "Ask whether a map from all planar lines to planar points can satisfy a dual incidence rule for every pair of nonparallel lines.",
    primaryDomain: "S5",
    secondaryTags: ["EUCLID"],
    methodTags: ["CONTRADICTION", "LEMMA-EXTRACTION", "AUXILIARY-OBJECT"],
    t25Targets: ["G2", "F4", "F5"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "The first official solution is elementary incidence geometry plus injectivity and contradiction; projective geometry is not required."
  },
  {
    id: "SMMC-2024-B4",
    year: 2024, session: "B", problem: 4, eastRelevant: true,
    synopsis: "Study reducibility modulo two of a symmetric three-variable polynomial family; prove infinitely many reducible cases and ask for the complete classification.",
    primaryDomain: "S1",
    secondaryTags: ["POLY", "FF", "MOD"],
    methodTags: ["FACTORIZATION", "NORMALIZATION", "CROSS-DOMAIN", "CONSTRUCTION"],
    t25Targets: ["A1", "A4", "M3", "F4"],
    t25Bridges: ["BR-N"],
    overlap: "red",
    bridgeNeeds: ["Polynomial algebra over finite fields", "Frobenius automorphism and finite-field extensions", "Unique factorisation over finite-field polynomial rings", "Irreducibility/reducibility theory beyond elementary factorization"],
    assessmentRole: "open-problem",
    classificationConfidence: "high",
    auditNote: "The official document gives solutions only to part (a) and explicitly records known partial results for part (b), citing research on cyclic codes and exceptional polynomials."
  },
  {
    id: "SMMC-2024-C1",
    year: 2024, session: "C", problem: 1, eastRelevant: false,
    synopsis: "Characterize the possible numbers of lattice points strictly inside a square centred at the origin.",
    primaryDomain: "S5",
    secondaryTags: ["LATTICE", "EUCLID", "MOD"],
    methodTags: ["SYMMETRY", "CONSTRUCTION", "INVARIANT", "BOUNDING"],
    t25Targets: ["G2", "F4"],
    t25Bridges: ["BR-N"],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "An irrational-slope construction makes boundary lattice points enter in rotational orbits of four, while 90-degree symmetry gives the converse."
  },
  {
    id: "SMMC-2024-C2",
    year: 2024, session: "C", problem: 2, eastRelevant: false,
    synopsis: "For an explicit cubic polynomial, determine all real points of period dividing two under iteration.",
    primaryDomain: "S1",
    secondaryTags: ["POLY", "FUNC"],
    methodTags: ["MONOTONICITY", "FACTORIZATION", "CONTRADICTION"],
    t25Targets: ["A1", "C3", "C4", "F5"],
    t25Bridges: [],
    overlap: "green",
    bridgeNeeds: [],
    assessmentRole: "transfer",
    classificationConfidence: "high",
    auditNote: "Strict monotonicity reduces two-cycles to fixed points, after which polynomial factorization finishes the problem."
  },
  {
    id: "SMMC-2024-C3",
    year: 2024, session: "C", problem: 3, eastRelevant: false,
    synopsis: "Let a_n count odd binomial coefficients in row n of Pascal's triangle; determine exactly when the Dirichlet-type series sum a_n/n^s converges.",
    primaryDomain: "S3",
    secondaryTags: ["SERIES", "MOD", "CONST"],
    methodTags: ["INDUCTION", "RECURRENCE-REFORMULATION", "BOUNDING", "CROSS-DOMAIN"],
    t25Targets: ["P2", "A5", "A2"],
    t25Bridges: ["BR-I", "BR-N"],
    overlap: "red",
    bridgeNeeds: ["Positive-series block comparison and convergence criteria", "Parity structure of Pascal's triangle / binary no-carry encoding", "Geometric block estimates for a non-geometric series"],
    assessmentRole: "development",
    classificationConfidence: "high",
    auditNote: "The official routes combine Pascal parity structure with series comparison; this reinforces the already-established SMMC infinite-series bridge."
  },
  {
    id: "SMMC-2024-C4",
    year: 2024, session: "C", problem: 4, eastRelevant: false,
    synopsis: "Students occupy random nonadjacent seats until no legal seat remains; determine the limiting expected occupied proportion.",
    primaryDomain: "S6",
    secondaryTags: ["RANDOM-PROCESS", "REC", "GF", "ODE"],
    methodTags: ["RECURRENCE-REFORMULATION", "GENERATING-FUNCTION", "CROSS-DOMAIN", "BOUNDING"],
    t25Targets: ["J1", "P4", "A5", "C3", "C6"],
    t25Bridges: ["BR-I"],
    overlap: "red",
    bridgeNeeds: ["Ordinary generating functions", "Generating-function differentiation of a recurrence", "Elementary first-order linear ODE solving", "Coefficient/asymptotic extraction for the limiting density"],
    assessmentRole: "development",
    classificationConfidence: "high",
    auditNote: "Expectation and first-step decomposition are T25-owned, but the official completion uses the generating-function/ODE bridge already seen in 2018."
  }
];
