export default [
[51,'Matrix products require matching inner dimensions and preserve factor order. Transposition reverses the order of a product.',
'For A=[[1,2],[0,1]],B=[[1,0],[3,1]], compute AB,BA,(AB)^T and B^T A^T. Explain the dimensions of each.',
'All2×2. AB=[[7,2],[3,1]],BA=[[1,2],[3,7]]. Both transposed-product displays equal[[7,3],[2,1]]. Thus AB≠BA.',
'Let C=[[1,2,3],[4,5,6]]. Compute CC^T and explain why C^T C has a different size.',
'CC^T=[[14,32],[32,77]] is2×2; C^T C is3×3. Inner dimensions are3 in the first product and2 in the second.'],
[52,'Elementary row operations preserve the solution set when they are reversible. Operate on the augmented matrix, including its right-hand column.',
'Solve x+y+z=3,2x+y+3z=6,x−y+z=1 by reversible row operations and verify.',
'Subtract first from third:−2y=−2 gives y=1. Second−2first:−y+z=0 gives z=1, then x=1. Substitution verifies all three.',
'A row operation multiplies a row by parameter a. Explain when it is reversible. Solve x+y=2,2x+2y=4 and describe the solution set dimension.',
'Reversible iff a≠0; a=0 can erase a constraint. Second equation redundant, (x,y)=(2−t,t),t∈R,an affine line of dimension1.'],
[53,'A subspace contains zero and is closed under linear combinations. A dependence relation is a nontrivial coefficient vector yielding zero.',
'Which sets in R³ are subspaces: x+y+z=0; x+y+z=1; xyz=0? Give proofs or counterexamples. Test dependence of(1,0,1),(0,1,1),(1,1,2).',
'First is a homogeneous kernel, hence subspace. Second lacks zero. Third not closed: (1,0,1)+(0,1,0)=(1,1,1). Vectors dependent since v3=v1+v2.',
'For polynomials degree≤2, test whether p(0)=p(1) defines a subspace and exhibit an explicit nonzero element.',
'Constraint is linear homogeneous and preserved under combinations. For p=a+bx+cx² it means b+c=0. x−x² is nonzero and satisfies it.'],
[54,'A basis must both span the space and be independent. Counting variables minus constraints works only after verifying constraint rank.',
'Find a basis and dimension of {(x,y,z,w):x+y+z=0,y+w=0}. Justify both basis properties.',
'Let y=s,z=t; x=−s−t,w=−s. Basis(−1,1,0,−1),(−1,0,1,0),dimension2; y,z coordinates force independence.',
'Find a basis and dimension for real symmetric2×2 matrices and for those with trace0.',
'Symmetric matrices[[a,b],[b,c]] have basis E11,E22,[[0,1],[1,0]],dimension3. Trace-zero uses[[1,0],[0,−1]] and offdiagonal basis,dimension2.'],
[55,'Consistency requires equal coefficient and augmented ranks. For a consistent n-variable system, its affine solution dimension is n−rank(A).',
'Classify solutions of x+y+z=1,2x+2y+2z=a. Give both ranks and solution dimension for every a.',
'Coefficient rank1 always. If a=2 augmented rank1,dimension2 with x=1−s−t,y=s,z=t. Otherwise augmented rank2, inconsistent; no affine solution dimension is assigned.',
'Can a3×5 matrix give exactly one solution to Ax=b? Prove your answer and identify possible dimensions when consistent.',
'Rank≤3<5,so nontrivial kernel and no unique solution. Consistent dimension5−rank∈{2,3,4,5}.'],
[56,'Separate parameter values where elimination pivots vanish. Rank inequalities bound possibilities without assuming invertibility.',
'For A=[[1,t],[t,1]], classify unique/no/infinitely many solutions of Ax=(1,1)^T for every real t.',
'Determinant1−t². For t≠±1 unique x1=x2=1/(1+t). At t=1 equations coincide, x1+x2=1. At t=−1 they demand x1−x2=1 and−x1+x2=1, inconsistent.',
'Prove rank(AB)≤min(rankA,rankB) for conformable matrices, using images and kernel or column spans.',
'Image AB lies in image A, giving first bound. A maps image B onto image AB; linear maps cannot increase dimension, giving second bound.'],
[57,'Inverse products reverse order. Trace is cyclic for conformable two-factor products, but not an arbitrary reordering of many factors.',
'For invertible square A,B prove (AB)^−1=B^−1 A^−1 by multiplication. Prove tr(AB)=tr(BA) from entries. State det(AB).',
'Both products with B^−1 A^−1 reduce to I. trAB=ΣiΣj aij bji=trBA. detAB=detA detB. These statements do not assert AB=BA.',
'If A is3×3 with detA=2, find det(3A),det(A^−1),det(A^T A). Is tr(A^−1)=1/trA generally true?',
'54,1/2,4 respectively. False: A=I3 gives3 versus1/3.'],
[58,'A determinant expansion can produce a recurrence. Establish initial cases, then solve or use the recurrence without dividing by possibly zero terms.',
'Let Dn be the determinant of the n×n tridiagonal matrix with2 on the diagonal and−1 on adjacent diagonals. Derive a recurrence and closed form, with D0=1.',
'Expansion yields Dn=2D(n−1)−D(n−2),D0=1,D1=2. Induction gives Dn=n+1,so never singular.',
'For u∈R^n nonzero classify singularity of I−c uu^T and its action on span(u) and its orthogonal complement.',
'On u eigenfactor1−c||u||²; on perpendicular vectors factor1. Singular iff c=1/||u||²,with kernel span(u).'],
[59,'A matrix is diagonalizable when it has a basis of eigenvectors. Algebraic multiplicity alone does not ensure enough eigenvectors.',
'For A=[[2,1],[0,2]], find eigenvalues/eigenspaces and decide diagonalizability. Contrast diag(2,2).',
'Only eigenvalue2,multiplicity2; eigenspace{(x,0)} dimension1,not diagonalizable. 2I has all vectors as eigenvectors and is diagonal already.',
'For B=[[2,1],[1,2]], produce P,D with B=PDP^−1 and verify.',
'Eigenpairs3 with(1,1),1 with(1,−1). P=[[1,1],[1,−1]],D=diag(3,1),P^−1=P/2. Direct multiplication verifies.'],
[60,'A polynomial identity can reduce all higher powers. Matrix square roots need not be unique, even when one natural root is available.',
'If A²=A prove A^n=A for n≥1 and derive (I+tA)^−1 when it exists, assuming A≠0.',
'Induction gives powers. Multiplication shows inverse I−tA/(1+t) for t≠−1. At t=−1 a nonzero image vector Av is in the kernel of I−A,so singular.',
'For B=[[2,1],[1,2]] find B^n for n≥0 and all real symmetric square roots that commute with B.',
'Using its distinct eigenbasis, B^n=1/2[[3^n+1,3^n−1],[3^n−1,3^n+1]]. A commuting matrix preserves each one-dimensional eigenspace; roots have independent eigenvalues±√3,±1, giving four symmetric matrices P diag(±√3,±1)P^−1.'],
[61,'A real symmetric matrix has orthogonal eigencoordinates. Positivity of its quadratic form is equivalent to positivity of all eigenvalues.',
'Classify definiteness of q=x²+2axy+y² for every real a, including singular boundary cases.',
'Matrix[[1,a],[a,1]] eigenvalues1+a,1−a. Positive definite |a|<1; semidefinite |a|=1; indefinite |a|>1. Never negative definite.',
'If symmetric A satisfies v^TAv≥0 for every v and trA=0, prove A=0. Explain why symmetry matters.',
'All eigenvalues nonnegative and sum0,so all0; spectral decomposition gives A=0. A nonzero skew-symmetric matrix has v^TAv=0 and trace0,so symmetry is essential.'],
[62,'An idempotent is a projection onto its image along its kernel. Orthogonal projection additionally needs symmetry under the usual Euclidean inner product.',
'For H=(1/n)11^T show H²=H,H^T=H and derive ||y||²=||Hy||²+||(I−H)y||². Identify image and kernel.',
'1^T1=n gives idempotence; symmetry direct. Hy orthogonal to residual since H(I−H)=0. Image constant vectors; kernel vectors with sum0.',
'For P=[[1,1],[0,0]], check idempotence and whether ||y||²=||Py||²+||(I−P)y||² holds for all y. For A=diag(2,0), find a G satisfying AGA=A.',
'P²=P but nonsymmetric. y=(0,1) gives left1,right1+2=3. G=diag(1/2,0) satisfies AGA=A; this generalized inverse need not be an ordinary inverse.'],
[63,'A two-sided limit exists only when both one-sided limits agree. Function value at the point is separate from the limiting value.',
'For f(x)=|x|/x,x≠0, find both limits at0 and decide the two-sided limit. Prove lim(x→2)(3x+1)=7 using ε,δ.',
'Left−1,right1,so no two-sided limit. Given ε>0 chooseδ=ε/3;0<|x−2|<δ implies |3x+1−7|<ε.',
'Let f(x)=x+1 for x<0 and2x+c for x≥0. Find c for continuity at0; give the one-sided limits for arbitrary c.',
'Left1,rightc,valuec. Continuity iff c=1.'],
[64,'Continuity at a point combines existence of a limit with equality to the function value. Two sequences approaching the point with different function limits refute existence.',
'Prove x sin(1/x), extended by0 at0, is continuous at0. Show sin(1/x) has no limit there.',
'Absolute value bounded by |x|→0. For sin take x_n=1/(π/2+2πn) giving1 and y_n=1/(3π/2+2πn) giving−1.',
'For rational x set f(x)=x and for irrational x set f(x)=−x. Determine all continuity points with justification.',
'At0,|f(x)|=|x| ensures continuity. At a≠0 rational and irrational sequences approaching a yield limits a,−a,distinct.'],
[65,'A derivative is a limit of difference quotients, not merely a rule to quote. Separate a finite increment from its limiting coefficient.',
'From the difference quotient derive the derivative of f(x)=x³ at arbitrary real a. State the exact increment f(a+h)−f(a).',
'Increment3a²h+3ah²+h³. Divide by h≠0 and let h→0 to obtain3a².',
'For f(x)=1/x derive f′(a) from first principles for every legal a. Explain the exclusions on a and h.',
'a≠0 and a+h≠0. Quotient[1/(a+h)−1/a]/h=−1/[a(a+h)] for h≠0; limit−1/a².'],
[66,'Differentiability implies continuity, but the converse fails. At a join compare one-sided difference quotients, not just derivatives away from the join.',
'For f(x)=x² when x<0 and ax+b when x≥0, find all a,b making f differentiable at0.',
'Continuity requires b=0; left difference quotient x→0,derivative0; right derivative a. Thus a=b=0.',
'Let f(0)=0,f(x)=x²sin(1/x) otherwise. Decide differentiability at0 and continuity of its derivative there.',
'f(x)/x=x sin(1/x)→0,so f′(0)=0. For x≠0 derivative2xsin(1/x)−cos(1/x),which oscillates and has no limit0.'],
[67,'Product and chain rules track different operations. A quotient derivative still inherits the original denominator restrictions.',
'Differentiate h(x)=(x²+1)³/(x−1), giving its domain and identifying each rule used.',
'Domain x≠1. h′=[6x(x²+1)²(x−1)−(x²+1)³]/(x−1)²,from chain and quotient rules.',
'Derive the product rule from a difference quotient under differentiability assumptions and use it for x²f(3x).',
'Add/subtract f(x+h)g(x),separate increments and use continuity of differentiable functions. Derivative2x f(3x)+3x² f′(3x),where f is differentiable at3x.'],
[68,'Logarithmic differentiation requires a domain where its logarithm is legal. Trigonometric derivatives use radians.',
'Differentiate x^x for x>0 and log(sin x) on its real domain. State the domains.',
'x^x=exp(xlogx),derivative x^x(logx+1). log(sin x) requires sinx>0,i.e.(2kπ,(2k+1)π); derivative cotx there.',
'Differentiate exp(−x²)cos(2x) and log|x| for x≠0.',
'First exp(−x²)[−2xcos2x−2sin2x]. Second1/x on each component of R\\{0}; absolute value keeps logarithm defined.'],
[69,'IVT supplies existence under continuity and a sign change. Uniqueness requires additional reasoning such as strict monotonicity.',
'Prove x³+x−1=0 has exactly one real root and locate it in(0,1), stating the role of each theorem.',
'Continuous polynomial has values−1,1 at0,1,so IVT gives existence. Derivative3x²+1>0 implies strict increase and at most one root.',
'Does a sign change prove a unique root? Give a continuous counterexample on a specified interval and count its roots there.',
'f(x)=x³−x on[−2,2] has endpoint values−6,6 but three roots−1,0,1. IVT alone does not give uniqueness.'],
[70,'Rolle bounds root counts via derivative zeros; MVT bounds differences via derivatives. Check continuity on the closed interval and differentiability inside.',
'If differentiable f:R→R satisfies f′(x)≥2 and f(0)=1, prove it has at most one zero. Prove or refute the claim that any zero lies at or left of−1/2; give the correct bound.',
'MVT gives f(y)−f(x)≥2(y−x) for y>x,so strictly increasing. A root r must be negative;1=f(0)−f(r)≥−2r,so r≥−1/2, not at or left. The requested bound is false: f(x)=4x+1 has r=−1/4. Correct range[−1/2,0).',
'For f:[0,1]→[0,1] continuous and differentiable inside with |f′|≤q<1, prove existence and uniqueness of a fixed point.',
'g=f−x has g(0)≥0,g(1)≤0,so IVT. If two fixed points existed,MVT bound|f(a)−f(b)|≤q|a−b| contradicts equality for a≠b.'],
[71,'Global optimization requires comparison of all admissible critical points and boundaries. An open boundary can yield a supremum that is not attained.',
'Find global extrema of f(x)=x³−3x on[−2,2], with every candidate checked.',
'f′=3(x²−1),critical±1. Values f(−2)=−2,f(−1)=2,f(1)=−2,f(2)=2. Max2 at−1,2;min−2 at−2,1.',
'Optimize x(1−x) on(0,1) and distinguish maximum,minimum,supremum,infimum.',
'Complete square1/4−(x−1/2)². Max/sup1/4 attained at1/2. Inf0 approached at endpoints but no minimum.'],
[72,'A Taylor approximation needs a remainder estimate to justify an error or limit. Specify the expansion point and the interval controlling the next derivative.',
'Using Taylor with remainder, show |e^x−1−x|≤(e/2)x² for |x|≤1 and evaluate lim(x→0)(e^x−1−x)/x².',
'Lagrange remainder=e^ξ x²/2 with ξ between0,x; bound e/2. Since ξ→0,ratio→1/2.',
'Approximate log(1+x) by x−x²/2 for |x|≤1/2 and give a rigorous cubic error bound.',
'Third derivative2/(1+t)³ has absolute value≤16 on that interval. Remainder≤16|x|³/6=(8/3)|x|³.'],
[73,'Definite substitution changes limits; integration by parts retains boundary terms. Absolute values require splitting where their inside expression changes sign.',
'Evaluate ∫₀²|x−1|dx and ∫₀¹x e^x dx, explaining the method.',
'First split at1:two triangles each1/2,total1. Parts for second gives[xe^x]₀¹−∫₀¹e^x dx=e−(e−1)=1.',
'Evaluate ∫₀¹2x/(1+x²)dx and ∫₀^π sin²x dx.',
'u=1+x²,limits1,2 yieldslog2. Half-angle identity givesπ/2.'],
[74,'Improper integrals have separate endpoint limits. Convergence at infinity and at zero generally impose different inequalities.',
'For real p find all p such that ∫₀^∞ x^p/(1+x²)dx converges. Justify both endpoints.',
'Near0 comparable to x^p,requiring p>−1. At infinity comparable to x^(p−2),requiring p<1. Thus−1<p<1; endpoints logarithmically diverge.',
'Classify ∫₁^∞1/[x(logx)^q]dx for real q, treating both1 and∞.',
'u=logx converts to∫₀^∞u^−q du. Near0 requires q<1;infinity requires q>1. No q gives full convergence.'],
[75,'Recognize both the mesh width and sample points. Riemann-sum convergence needs integrability, not just resemblance to an integral.',
'Find lim(n→∞)(1/n)Σ(k=1 to n)(k/n)² and justify as a Riemann sum.',
'Continuous x² on[0,1],uniform mesh1/n,right endpoints. Limit∫₀¹x²dx=1/3.',
'Find lim(n→∞)Σ(k=1 to n)n/(n²+k²), identifying the function and interval.',
'Each term=(1/n)/(1+(k/n)²). Continuous integrand on[0,1],limit arctan1−arctan0=π/4.'],
[76,'For a positive product, take its logarithm and justify the resulting sum limit. A singular logarithmic endpoint needs a separate bound or monotonicity argument.',
'Find lim(n→∞)[Π(k=1 to n)(1+k/n)]^(1/n), with a justified logarithmic Riemann sum.',
'Log tends∫₀¹log(1+x)dx=2log2−1. Exponentiating gives4/e.',
'Find lim(n→∞)(n!/n^n)^(1/n) without citing Stirling. Control the singularity of logx at0.',
'For increasing log on[1,n],integral comparison gives ∫₁^n logx dx≤log(n!)≤∫₁^n logx dx+logn. Divide by n and subtractlogn:both bounds→−1; exponential limit e^−1.'],
[77,'Complete squares before naming a conic. The constant and quadratic signs can also yield a point, empty set or intersecting lines.',
'Classify x²+4y²−2x+8y+c=0 for every c, including degenerate cases.',
'(x−1)²+4(y+1)²=5−c. For c<5 an ellipse; c=5 a single point(1,−1); c>5 empty.',
'Classify x²−y²=k for all real k, describing the degenerate case and axes.',
'k>0 hyperbola opening along x; k<0 along y after rearrangement. k=0 is union of lines y=±x, not a nondegenerate hyperbola.'],
[78,'Focus/directrix definitions depend on conic type and axis orientation. The circle has eccentricity0 and no finite directrix in the usual distance-ratio representation.',
'For x²/25+y²/9=1 find foci,eccentricity,directrices and verify the focus-distance relation at(5,0).',
'a5,b3,c4. Foci(±4,0),e=4/5,directrices x=±25/4. For right focus distance1, right directrix distance5/4,ratio4/5.',
'For y²=8x find focus,directrix,eccentricity. For x²+y²=9 explain the eccentricity/directrix exception.',
'4p=8,p2:focus(2,0),directrix x=−2,e=1. Circle radius3 has c0,e0; no finite directrix supports distance=e·distance because focus-distance would not be0.'],
[79,'A parametrisation must satisfy the conic equation and its domain must cover the intended points. Trigonometric and rational parameters have different coverage exceptions.',
'Parametrise x²/9+y²/4=1 and locate the point for t=π/6. State coverage and repetitions.',
'x=3cost,y=2sint,t∈[0,2π) covers each point once; atπ/6,(3√3/2,1). Extending to R repeats every2π.',
'For parabola y²=4ax with a>0, prove (at²,2at) parametrises every real point uniquely and find t for y=−6a.',
'Substitution verifies equation; any point has t=y/(2a),forcing x=at². t=−3 gives(9a,−6a).'],
[80,'A tangent derived by implicit differentiation may be vertical where its solved slope formula divides by zero. Use the gradient equation to preserve these cases.',
'Find the tangent and normal to x²/9+y²/4=1 at(0,2) and at(3,0). Explain any vertical-line exceptions.',
'Tangent gradient formula xx0/9+yy0/4=1. At(0,2):tangent y=2,normal x=0. At(3,0):tangent x=3,normal y=0. A single finite slope expression misses the latter tangent.',
'For y²=4ax,a>0,derive tangent at(at²,2at) and the normal for t≠0, then handle t=0.',
'Tangent ty=x+at² (from gradient). For t≠0 tangent slope1/t,normal slope−t: y−2at=−t(x−at²). At0 tangent x=0 and normal y=0; the same normal formula gives y=0.']
];
