export default [
[27, 'State the random experiment before counting. Ordered outcomes can be equiprobable even when a statistic or unordered summary is not.',
'Two fair dice are rolled. Specify an equiprobable sample space, the distribution of their sum, and whether the eleven possible sums are equiprobable.',
'Ω={(i, j):1≤i, j≤6}, each1/36. Counts for sums2, ..., 12 are1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1. Thus the sums are not equiprobable.',
'A bag has distinguishable balls R1, R2, B. Draw two without replacement in order. List the elementary outcomes and compute the probability of one red and one blue.',
'Six ordered distinct pairs equally likely. Four have one blue and one red, so probability2/3; unordered colour categories are not equally likely.'],
[28, 'Permutations retain order; combinations identify orders as one selection. Division by a symmetry count is valid only when the multiplicity is uniform.',
'From eight distinct people choose a chair, secretary and treasurer, then compare with choosing an unordered committee of three. Justify both counts.',
'8·7·6=336 ordered assignments. Each committee has3!=6 assignments, hence C(8, 3)=56.',
'How many five-letter strings from A, B, C have exactly two As and one B? Repetition is allowed; explain the role of indistinguishable repeated letters.',
'The remaining two letters must be C. Choose A positions C(5, 2), then B position3:30=5!/(2!2!).'],
[29, 'Restrictions often become simpler by choosing positions or gaps after placing a complementary group. Check feasibility and avoid counting the same arrangement twice.',
'Arrange four distinct boys and three distinct girls in a row with no adjacent girls. Count and justify.',
'Arrange boys4!, choose3 of5 gaps, permute girls3!:1440. Each legal arrangement has exactly one such description.',
'How many binary strings of length8 contain exactly three ones with none adjacent? Give a bijection or gap argument.',
'If positions i1<i2<i3 satisfy successive gaps≥2, map to i1, i2−1, i3−2, a3-subset of{1, ..., 6}. Count C(6, 3)=20.'],
[30, 'Identify which symmetries count as the same outcome. Cyclic rotations act freely on arrangements of distinct objects; repeated objects may require a separate argument.',
'Six distinct people sit around an unlabelled circular table; rotations are identical but reflections are different. Count arrangements. Find the coefficient of x²y³z in(x+y+z)^6.',
'Fix one person:5!=120. Coefficient6!/(2!3!1!)=60, selecting positions for each symbol.',
'Count even permutations of four distinct symbols by a bijection. Count binary strings of length6 with an even number of ones.',
'Swapping the first two entries bijects even and odd permutations; 24/2=12. Flipping the first bit exchanges parity, so64/2=32.'],
[31, 'Inclusion-exclusion corrects overlap. The union bound remains valid without independence, but it can exceed1 and then supplies no useful improvement over the trivial bound.',
'Events A, B have probabilities.6, .5 and intersection.2. Find union and neither. Prove P(A∪B)≤P(A)+P(B) and state its equality condition.',
'Union.9, neither.1. Indicator identity gives union=sum−intersection. Equality iff P(A∩B)=0, which need not mean the intersection is empty.',
'Three events each have probability.1. Bound their union without dependence information. Can the union be.1? Can it be.3? Exhibit models.',
'.1≤P(union)≤.3. Identical events attain.1; three disjoint intervals of length.1 in uniform[0, 1] attain.3.'],
[32, 'Countable additivity implies continuity from below; continuity from above requires finite measure, automatic for probability. Track increasing versus decreasing sets.',
'For independent fair coin tosses let An mean at least one head in the first n tosses. Compute P(An), identify the set limit and justify its probability.',
'An increases to the event of a head at some finite time. P(An)=1−2^−n, so continuity from below gives probability1; the all-tail sequence is not impossible as a set element but has probability0.',
'For U uniform(0, 1), let Bn={U≤1/n}. Identify the decreasing intersection and its probability. Prove continuity from above using complements.',
'Intersection is empty on sample space(0, 1), hence probability0, also limit1/n. Complements increase; P(intersection Bn)=1−limP(Bn^c)=limP(Bn).'],
[33, 'Conditioning renormalizes masses inside the conditioning event, which must have positive probability. It can change equiprobability among summaries.',
'Two fair dice are rolled. Given their sum is8, find the law of the first die and probability that at least one die is6.',
'Allowed pairs(2, 6), (3, 5), (4, 4), (5, 3), (6, 2), each conditional probability1/5. First die uniform on{2, ..., 6}; at least one6 probability2/5.',
'A card is drawn uniformly from a standard52-card deck. Given it is a face card(J, Q, K), find probability it is a heart. Is conditioning on “a red black card” defined?',
'3 hearts among12 face cards:1/4. The contradictory event has probability0; elementary conditional probability is not defined for it.'],
[34, 'Bayes reverses a conditional direction using prior weights and a partition. A test sensitivity is not the probability of the underlying state after a positive result.',
'An item comes from factory A with probability.7, otherwise B. Defect rates are.02 and.05. Given a defect, find probability of B, deriving the denominator.',
'Defect probability.7·.02+.3·.05=.029. Joint B and defect=.015; posterior15/29.',
'A disease has prevalence.01. A test has sensitivity.9 and specificity.95. Find the probability of disease given a positive test.',
'Positive mass.009+.99·.05=.0585. Posterior.009/.0585=2/13. False positives dominate because noncases are common.'],
[35, 'Independence is the probability equation P(A∩B)=P(A)P(B). Disjointness is the set equation A∩B=∅; a null intersection need not be empty.',
'For U uniform[0, 1], A=[0, 1/2], B=[1/2, 1], test disjointness and independence. Can two disjoint positive-probability events be independent?',
'Intersection{1/2} is nonempty but null. P(A)P(B)=1/4≠0, so dependent. Disjoint positive masses have intersection0 but positive product, hence cannot be independent.',
'For two independent fair bits X, Y let A={X=1}, B={Y=1}. Test independence and disjointness. What happens if one event has probability0?',
'Intersection probability1/4=product, so independent, yet not disjoint. Any null event is independent of every event since both intersection and product have probability0.'],
[36, 'Pairwise independence does not control higher intersections. Conditioning can create or remove dependence; test the conditional factorization directly.',
'Let X, Y be independent fair bits and Z=X xor Y. Show pairwise independence, refute mutual independence, and test X, Y independence given Z=0.',
'Each bit is fair; each pair has four equally likely pairs. P(X=0, Y=0, Z=0)=1/4≠1/8. Given Z=0, pairs00, 11 have half each; marginal halves give product1/4 but joint00 is1/2.',
'A fair coin selects Θ∈{1/4, 3/4}. Given Θ, X, Y are independent Bernoulli(Θ). Determine whether X, Y are independent without conditioning.',
'EX=EY=1/2; E(XY)=EΘ²=(1/16+9/16)/2=5/16≠1/4. They are conditionally independent but marginally dependent.'],
[37, 'An indicator equals1 when its event occurs and0 otherwise. Define a payoff as a function on elementary outcomes before assigning a distribution.',
'Roll three fair dice. Let N count sixes and W pay5 if at least one six appears, otherwise−1. Express N as indicators and give the law of W.',
'N=Σ(i=1 to3)1{Di=6}. P(W=5)=1−(5/6)³=91/216; P(W=−1)=125/216.',
'A random permutation of{1, ..., n} is selected uniformly. Define the number F of fixed points by indicators and explain why the indicators need not be independent.',
'F=Σ1{π(i)=i}. For n=2 both indicators coincide, so not independent. Their definition uses the same constrained permutation.'],
[38, 'Expectation is linear without independence. Dependence matters for products and variance, not for the sum identity itself.',
'For a uniform random permutation of n≥2 symbols find the expected number of fixed points using indicators. Explain why independence is unnecessary.',
'Each position is fixed in(n−1)! of n! permutations, probability1/n. Sum expectations n/n=1 regardless of dependence.',
'Draw n times independently and uniformly from m labels. Find the expected number of distinct labels observed; do not assume label-appearance indicators independent.',
'For each label probability seen=1−(1−1/m)^n. Sum over labels gives m[1−(1−1/m)^n].'],
[39, 'Var(sum)=sum variances plus twice pair covariances. Sampling without replacement creates dependence that must be retained.',
'Draw two values without replacement from{1, 2, 3}. Compute each mean and variance, their covariance and variance of their sum.',
'Means2, variances2/3. E(XY)=(2+3+2+6+3+6)/6=11/3; covariance−1/3. Sum variance4/3−2/3=2/3.',
'Let Y=2X+3 with Var(X)=4. Find Cov(X, Y), Var(X+Y) and correlation. Contrast with the result of incorrectly assuming independence.',
'Cov8, sum varianceVar(3X+3)=36; correlation1. Independence would give4+16=20 and is false.'],
[40, 'Overlapping sums share random terms. Collect coefficients of the independent inputs, or count covariance overlaps explicitly.',
'Let iid Xi have mean μ and variance σ². For n≥1 define Sn=Σ(i=1 to n)(Xi+X(i+1)). Find mean and variance.',
'Sn=X1+2Σ(i=2 to n)Xi+X(n+1). Mean2nμ; variance[1+4(n−1)+1]σ²=(4n−2)σ², including n=1.',
'Let Y0=0 and Yk=aY(k−1)+εk, where independent εk have mean0, varianceτ². Derive mean and variance, including a²=1.',
'Yk=Σ(j=1 to k)a^(k−j)εj. Mean0; varianceτ²Σ(j=0 to k−1)a^(2j), equalτ²(1−a^(2k))/(1−a²) if a²≠1, otherwise kτ².'],
[41, 'A binomial counts independent trials with a fixed success probability. A hypergeometric counts successes in uniform sampling without replacement.',
'A population has5 red and7 blue objects; choose4 uniformly without replacement. Find probability exactly2 are red and compare with4 replacement draws.',
'Without replacement C(5, 2)C(7, 2)/C(12, 4)=14/33. With replacement C(4, 2)(5/12)²(7/12)². The latter has independent Bernoulli trials.',
'Derive P(X=k) and the support when n objects are selected without replacement from N with K marked. Explain why support endpoints matter.',
'P=C(K, k)C(N−K, n−k)/C(N, n), max(0, n−N+K)≤k≤min(n, K), integer k. Outside that range one required selection is impossible.'],
[42, 'Multinomial counts sum to n, so they are generally dependent. Condition on one count to renormalize the probabilities of the remaining categories.',
'In n independent trials categories have probabilities p1, p2, p3>0 summing1. Derive means, variances and Cov(N1, N2). Find N1 conditional on N3=k.',
'ENi=npi, VarNi=npi(1−pi). Within a trial category indicators have product0, covariance−p1p2; across trials covariance0, hence−np1p2. Conditional law Bin(n−k, p1/(p1+p2)).',
'For n=10, p=(.2, .3, .5), find E(N1+N2), Var(N1+N2), and E(N1|N3=4).',
'Sum Bin(10, .5):mean5, variance2.5. Conditional mean6·.2/.5=2.4.'],
[43, 'Waiting time can count trials through success or failures before success. Declare the convention and support before using a geometric/negative-binomial formula.',
'Independent trials succeed with p∈(0, 1). Derive the law, mean and memorylessness of T, trials through first success. Give the corresponding failures count.',
'P(T=t)=(1−p)^(t−1)p, t≥1; ET=1/p by first-step recursion or tail sum. P(T>s+t|T>s)=(1−p)^t=P(T>t). F=T−1 has support0, ... and mean(1−p)/p.',
'Derive the law of the number T of trials through the rth success. Explain the binomial coefficient and support.',
'P(T=t)=C(t−1, r−1)p^r(1−p)^(t−r), t≥r. Last trial succeeds and preceding t−1 contain r−1 successes. Mean r/p by summing r independent geometric waits.'],
[44, 'Poisson sums require independence. Factorial moments follow by shifting a convergent nonnegative series. A rare-event approximation needs a limiting regime.',
'For X Poisson(λ), derive E[X(X−1)] and VarX. For independent X, Y with parametersλ, μ derive the distribution of X+Y.',
'Shifting the series gives factorial momentλ²; EX=λ, so Varλ. Convolution gives e^(−λ−μ)(λ+μ)^k/k!, hence Poisson(λ+μ).',
'If Xn~Bin(n, λ/n), prove P(Xn=k)→e^−λ λ^k/k! for each fixed nonnegative integer k and n large enough. State what is fixed.',
'Expand C(n, k)(λ/n)^k(1−λ/n)^(n−k); the finite product n(n−1)…/n^k→1 and power→e^−λ. λ and k fixed, n→∞; this is pointwise mass convergence, not equality at finite n.'],
[45, 'An average gains precision through covariance structure. Identical marginals alone do not give the iid variance formula.',
'For independent Xi with common meanμ, varianceσ² derive E Xbar and Var Xbar. Repeat when all pair covariances equal c.',
'Meanμ. Independent varianceσ²/n. With covariance c, variance[ nσ²+n(n−1)c]/n²=σ²/n+(n−1)c/n; the proposed covariance matrix must be feasible.',
'Let Xi=Z+εi with all variables independent, VarZ=τ², Varεi=σ² and means0. Find Var Xbar and its large-n limit.',
'Xbar=Z+εbar, varianceτ²+σ²/n→τ². Common noise is not averaged away.'],
[46, 'The identity Σ(Xi−Xbar)²=Σ(Xi−μ)²−n(Xbar−μ)² explains the n−1 correction. Normality is unnecessary for unbiasedness.',
'For iid data with finite varianceσ² and n≥2 prove S²=Σ(Xi−Xbar)²/(n−1) is unbiased. Give the bias with denominator n.',
'Take expectations in the identity: nσ²−n·σ²/n=(n−1)σ². Denominator n expectation(n−1)σ²/n, bias−σ²/n.',
'If X1=…=Xn=Z with VarZ>0, compute S² and explain why the usual unbiasedness proof no longer applies.',
'S²=0 always. Independence (or suitable covariance conditions) fails, so Var Xbar=VarZ, notσ²/n; identical marginals alone do not justify the correction.'],
[47, 'Report conventions: population-style descriptive variance uses n, sample variance uses n−1; quantile definitions can differ on finite data.',
'For data1, 2, 2, 5, 10 compute mean, median, population-denominator variance and sample variance. Define quartiles by medians of the lower and upper halves and compute them.',
'Mean4, median2, sum squared deviations54; descriptive variance54/5=10.8, sample13.5. Excluding the median, lower half1, 2 gives Q1=1.5, upper5, 10 gives Q3=7.5.',
'For data0, 0, 1, 3 find the empirical CDF and its left quantile q(p)=inf{x:F(x)≥p} at p=.5, .75. Contrast q(.5) with the average-of-middle-two median.',
'CDF0 below0, .5 on[0, 1), .75 on[1, 3), 1 at/above3. q(.5)=0, q(.75)=1; average middle median.5. Both conventions must be named.'],
[48, 'Maintain count, sum and sum of squares for updates. Standardized central moments require positive variance and their finite-sample bias corrections are separate conventions.',
'A dataset has n=4, sum10, sum squares30. Add x=5. Find the new mean and sample variance. State the effect of y=a+bx on mean, variance and standardized third central moment for b≠0.',
'New n5, sum15, squares55, mean3; sample variance(55−45)/4=2.5. Mean a+bmean, variance b²variance; standardized skewness multiplied by sign(b).',
'For equal masses at−1 and1, compute standardized skewness and excess kurtosis using population central moments. Explain the zero-variance exception.',
'Mean0, variance1, third moment0, fourth1; skewness0, excess1−3=−2. With variance0 denominators vanish, so these standardized measures are undefined.'],
[49, 'Pearson correlation uses centered numerical values and requires positive variances. Spearman is Pearson correlation of ranks; ties require a stated rank convention.',
'For x=(1, 2, 3), y=(1, 4, 9) compute Pearson and Spearman correlations, using average ranks for ties if any. State existence conditions.',
'Centered x=(−1, 0, 1), centered y=(−11/3, −2/3, 13/3). Crosssum8, Sxx2, Syy98/3, so r=8/√(196/3)=4√3/7. Ranks identical, Spearman1. Both rank/value variances must be nonzero.',
'For x=(1, 1, 2), y=(1, 2, 3) compute average-rank Spearman correlation. Is the no-tie shortcut1−6Σd²/[n(n²−1)] valid here?',
'Ranks x=(1.5, 1.5, 3), y=(1, 2, 3), centered crosssum1.5, SS1.5 and2, so r=√3/2. The uncorrected no-tie shortcut is invalid.'],
[50, 'Regression slopes depend on direction and units: b_yx=r sy/sx and b_xy=r sx/sy. Their product is r², not generally1.',
'Given regression slopes of y on x and x on y are.8 and.2, find correlation and sy/sx. Can both lines be inverted to represent the other regression?',
'Product.16 gives r=.4 since slopes positive. sy/sx=.8/.4=2. Inversion would require product1, so not here.',
'Let X take−1, 0, 1 equally and Y=X². Compute covariance and correlation; decide whether zero correlation implies independence.',
'EX0, EY2/3, EXY0, so covariance0. Variances2/3 and2/9 positive, correlation0. Y is determined by X and nonconstant, hence dependent (e.g. X=0 iffY=0).']
];
