export default [
[119,'Bias is EθT−g(θ); MSE equals variance plus squared bias when second moments exist. State the estimand before comparing formulas.',
'For iid Xi with meanμ,varianceσ²,compare T=Xbar and U=cXbar as estimators of μ. Derive bias,variance,MSE for fixed real c.',
'T bias0,variance/MSEσ²/n. U bias(c−1)μ,variance c²σ²/n,MSE c²σ²/n+(c−1)²μ².',
'For the same assumptions,find bias of Xbar² for μ². Is its MSE determined by μ,σ²,n alone?',
'E Xbar²=μ²+σ²/n,biasσ²/n. MSE requires E Xbar⁴,which may not be finite or determined by those two moments;additional information is needed.'],
[120,'An estimator comparison can depend on the unknown parameter. Keep covariances when combining dependent estimators; a pointwise winner need not dominate everywhere.',
'For Xi iid N(μ,1),compare Xbar and Xbar/2 by MSE for μ. Find the exact parameter region where shrinkage improves risk.',
'Risks1/n and1/(4n)+μ²/4. Shrinkage better iff μ²<3/n,equal at boundary,worse outside. No uniform dominance.',
'For iid Xi meanμ,varianceσ²,n≥2,let T=Xbar and U=X1. Find Cov(T,U) and Var(aT+(1−a)U);minimize over real a.',
'Covσ²/n. Varianceσ²[a²/n+(1−a)²+2a(1−a)/n]=σ²[1/n+(1−1/n)(1−a)²]. Minimum at a=1 ifσ²>0;all a ifσ²=0.'],
[121,'Method of moments matches theoretical moments to empirical ones. It need not equal maximum likelihood or be unbiased, and the resulting parameter must be admissible.',
'For Xi iid uniform(0,θ),θ>0,derive the first-moment estimator and its bias/variance. Does it always exceed the sample maximum?',
'E X=θ/2,so θhat=2Xbar,unbiased,varianceθ²/(3n). It need not exceed max:sample(.1,.1,.9) gives2mean≈.733<.9,so it can be incompatible with that sample support.',
'For iid exponential rateλ>0,derive a first-moment estimator and explain whether solving moments proves unbiasedness.',
'E X=1/λ gives λhat=1/Xbar when meanpositive. Nonlinear inversion does not preserve expectation;for n>1,ES^−1=λ/(n−1),so Eλhat=nλ/(n−1);for n1 expectation diverges.'],
[122,'Two-moment equations may have multiple or inadmissible solutions. Empirical central variance with denominator n is the difference of the first two raw empirical moments.',
'For Gamma(shape α,rate λ),derive method-of-moments estimators from sample mean m>0 and empirical variance v>0. Handle v=0.',
'm=α/λ,v=α/λ² imply αhat=m²/v,λhat=m/v. If v0 and m>0,no finite positive α,λ fit both;do not divide by0.',
'For uniform(a,b),a<b,derive moment estimates from m and v>0. Does that construction automatically guarantee every observation falls between the fitted endpoints?',
'ahat=m−√(3v),bhat=m+√(3v). No:sample(0,0,0,0,10),m2,v16 gives upper2+√48<10. Moment fitting is not a support-constrained likelihood fit.'],
[123,'Likelihood is the joint law of what was recorded, including support. Rounding/censoring changes likelihood contributions from densities to event probabilities.',
'For exact positive iid exponential observations with rateλ,derive its MLE and check the maximum. For iid uniform(0,θ) use density1/θ on[0,θ] and derive the MLE when sample maximum M>0.',
'Exponential L=λ^n exp(−λΣxi),unique maximum n/Σxi since log second derivative−n/λ². Uniform L=θ^−n1{θ≥M},decreasing on[M,∞),maximumθ=M under the specified closed-endpoint version.',
'Only integer floors Ki=floorXi of exponential(rateλ) data are recorded. Derive the likelihood and MLE,including all Ki=0.',
'Let q=e^−λ∈(0,1),L=(1−q)^n q^S withS=ΣKi. IfS>0,qhat=S/(n+S),λhat=log(1+n/S). IfS0,L increases asλ→∞;supremum1 is not attained at finiteλ.'],
[124,'Support-dependent likelihoods can maximize on boundaries or several disconnected sets. Specify the density convention and distinguish a maximum from an unattained supremum.',
'Xi have density1 on[θ,θ+1],θ∈R. Characterize the full MLE set from observations with range≤1. What if the range exceeds1?',
'All data legal iff θ≤minxi and θ≥maxxi−1. Likelihood1 on[max−1,min],so every point there maximizes. Range>1 gives zero likelihood for everyθ and indicates data outside the model;no informative fitted support.',
'For a single positive observation x from density1/θ on0<x<θ,θ>0,does an MLE exist? Contrast with the closed support convention0≤x≤θ.',
'Open support likelihoodθ^−1 forθ>x,zero otherwise;supremum1/x approached from above,not attained. Closed version attains atθ=x. Endpoint density conventions matter for formal pointwise likelihood statements.'],
[125,'Invariance maximizes over parameter fibers: apply the target map to an MLE, accounting for nonuniqueness and restrictions. It does not assert unbiasedness.',
'From positive exponential(rateλ) data derive the MLE of the median and of Pλ(X>c),c>0.',
'λhat=1/Xbar. Median(log2)/λ gives Xbar log2;survival e^−λc gives exp(−c/Xbar). Both by invariance,not a claim of unbiasedness.',
'For Bernoulli data with proportion phat,find MLEs of p² and p(1−p) overp∈[0,1]. Explain noninjectivity of the second map.',
'Invariance gives phat² and phat(1−phat). Even though p and1−p have same second target value,the global likelihood maximizer maps to a global maximizer of profile likelihood over target fibers.'],
[126,'Constrained normal-mean MLEs minimize a squared distance over the feasible set. Solve the constrained problem, then verify feasibility and global optimality.',
'Independent Xi~N(μi,σ²) with knownσ² and constraintΣμi=0. For observed xi,find the MLE vector.',
'MinimizeΣ(xi−μi)² subjectsum0. Lagrange equations give μihat=xi−xbar. Residual is constant vector orthogonal to constraint subspace;Pythagoras proves unique minimum.',
'Independent X,Y~N(θ,1) withθ∈[0,1]. Find the constrained MLE for any observations x,y.',
'Unconstrained minimizer m=(x+y)/2;objective=constant+2(θ−m)². Project to interval:max(0,min(1,m)). Includes both boundary cases.'],
[127,'Sufficiency is about retaining all sample information on the parameter. Factorization must include parameter-dependent support indicators.',
'For iid uniform(0,θ),using closed support,prove the sample maximum sufficient. Is it valid to drop the support from the factorization?',
'Jointθ^−n1{0≤minxi}1{maxxi≤θ};gθ(M)=θ^−n1{M≤θ},h=1{min≥0}. Dropping support would falsely suggest the data do not affect parameter admissibility.',
'For iid Bernoulli(p),prove S=ΣXi sufficient and describe the conditional sample law given S=s for0<p<1.',
'Jointp^s(1−p)^(n−s) on binary vectors,factorization. Given S=s,all C(n,s) vectors equally likely,independent ofp.'],
[128,'A one-to-one recoding preserves sufficiency. A many-to-one coarsening can discard parameter information; use a parameter-dependent conditional law to demonstrate loss.',
'For two iid Exp(rateλ) observations,show sum S sufficient and determine whether maximum M alone is sufficient. Avoid using isolated zero-probability sample points as a conditional argument.',
'Jointλ²e^−λS on positive quadrant proves sum sufficient. Given max=m,the minimum has densityλe^−λt/(1−e^−λm),0<t<m,depending onλ. Thus max is not sufficient.',
'For a Bernoulli sample of size2,compare S,the one-to-one statistic3S+1,and parity S mod2 for sufficiency.',
'S sufficient;3S+1 invertibly recodes it. Given even parity,probabilityS=2 is p²/[p²+(1−p)²],parameter-dependent,so parity not sufficient forp∈(0,1).'],
[129,'Conditioning an unbiased square-integrable estimator on a sufficient statistic preserves unbiasedness and cannot increase variance. The conditional expectation must be computed.',
'For iid Bernoulli(p),let U=X1 and S=ΣXi,n≥2. Compute E(U|S),show unbiasedness and compare variances.',
'Exchangeability conditional on S yields E(X1|S)=S/n. Meanp,variancep(1−p)/n versusp(1−p) forU. Strict improvement for interiorp andn>1.',
'For iid Poisson(λ),estimate e^−λ by U=1{X1=0}. Find its conditional expectation given S=ΣXi and state why variance cannot increase.',
'GivenS=s,X1~Bin(s,1/n),so estimator(1−1/n)^S,n≥2. Iterated expectation preserves EU=e^−λ. Total variance gives VarU=VarE(U|S)+EVar(U|S).'],
[130,'Minimum-variance certification has distinct routes. Lehmann–Scheffé needs complete sufficiency and unbiasedness; Cramér–Rao needs regularity and attainment of its bound.',
'For iid Poisson(λ),λ>0,certify Xbar as UMVU using the supplied fact that S=ΣXi is complete sufficient. Separately derive Fisher information and certify attainment of the Cramér–Rao bound.',
'Xbar=S/n is unbiased and a function of complete sufficientS,hence UMVU. ScoreS/λ−n,information n/λ;support parameter-independent and regular differentiation applies. Bound for unbiasedλ estimatorλ/n equals VarXbar.',
'For iid Exp(rateλ),use scaleθ=1/λ>0. Given sum complete sufficient,certify Xbar forθ by both completeness and information. Do not infer one certificate from the other.',
'Xbar unbiasedθ and function of sum gives UMVU. Scale score−n/θ+S/θ²,information n/θ² under positive fixed support. Boundθ²/n attained byVarXbar;both routes separately valid.'],
[131,'Size is a null rejection probability (a supremum for composite nulls). Power is the rejection probability as a function of the true parameter; Type II error is one minus power under an alternative.',
'X~Bin(4,p). Reject H0:p=.5 for X≥3. Compute actual size,power atp=.75,and Type II error there.',
'Size(4+1)/16=5/16. Power4(.75)³(.25)+(.75)^4=189/256. TypeII67/256.',
'For X~N(μ,1),reject H0:μ≤0 ifX>1.645. Express size and power inΦ and locate the least favorable null.',
'Power1−Φ(1.645−μ),increasing inμ. Supremum overμ≤0 occursμ0,size1−Φ(1.645),approximately.05.'],
[132,'A p-value uses the realized statistic and a specified extremeness ordering under the null. It is not the posterior probability that the null is true.',
'For X~Bin(4,.5),observedX=3,find the upper-tail p-value. If five tests each have size≤.01,what familywise bound follows without independence?',
'P0(X≥3)=5/16. Union bound familywise≤.05,regardless of dependence. Neither value is P(H0 true|data).',
'For a two-sided standard-normal test observedz=−2,express the p-value. Explain why selecting the direction after looking at the sign and reporting a one-sided tail miscalibrates the original two-sided question.',
'p=2[1−Φ(2)]. Post-selecting direction and using1−Φ(|z|) omits the equally extreme opposite tail;under the null either sign can trigger rejection.'],
[133,'Neyman–Pearson ranks outcomes by alternative/null likelihood ratio. Support-zero cases need explicit treatment before taking logarithms.',
'For X~Bin(n,p),compare simple H0:p=p0 and H1:p=p1 with0<p0<p1<1. Derive the likelihood ratio ordering.',
'Ratio(p1/p0)^x[(1−p1)/(1−p0)]^(n−x);successive ratio factor p1(1−p0)/[p0(1−p1)]>1. Thus large x gives stronger alternative evidence.',
'For one Exp(rateλ) observation,compare H0:λ=1,H1:λ=2. Which tail is most powerful and why?',
'L1/L0=2e^−x decreasing inx,so small observations have largest ratio. Reject on a lower tail,with size calibrated under Exp1.'],
[134,'Discrete tests may require randomization at a boundary to attain an exact target size. A randomization probability is part of the testing rule.',
'On outcomes0,1,2,null masses(1/2,1/3,1/6),alternative masses(1/6,1/3,1/2). Construct the most powerful test of size1/4 and compute power.',
'Ratios1/3,1,3. Reject2 (null1/6),randomize at1 withr satisfying1/6+r/3=1/4,so r1/4. Power1/2+(1/4)(1/3)=7/12.',
'For X~Bernoulli(p),testp=.2 againstp=.8 at exact size.1. Give the MP rule and power.',
'Outcome1 ratio4 versus.25 for0. Reject at1 with probability.5 and never at0. Size.2·.5=.1,power.8·.5=.4.'],
[135,'Normal tests depend on which parameters are known. A chi-square variance pivot uses normality; a mean t pivot needs sample variance and independence.',
'For iid normal data with unknownμ,σ²,n≥2,derive a two-sided levelα test of μ=μ0 and a two-sided test ofσ²=σ0². Use lower-tail quantiles qν(p).',
'Mean statistic√n(Xbar−μ0)/S~t(n−1);reject absolute value>t_(n−1)(1−α/2). Variance statistic(n−1)S²/σ0²~χ²(n−1);reject belowq(α/2) oraboveq(1−α/2). Equal-tail variance test stated,not claimed UMP.',
'For normal Xi with knownσ²,derive a one-sided levelα test μ≤μ0 versusμ>μ0. Why is substituting an arbitrary variance estimate into the z cutoff not automatically exact?',
'Z=√n(Xbar−μ0)/σ,rejectZ>Φ^−1(1−α). Unknown variance changes the finite-sample null law;with usualS under iid normality it is t,not exactlyz.'],
[136,'Two-group ANOVA and pooled two-sample t agree under the same independent normal equal-variance model. Unequal known variances instead give a different exact normal pivot.',
'For independent normal groups of sizes n1,n2 with common unknown variance,derive the pooled t test for equal means and prove the two-group ANOVA F equals t².',
'Sp²=[(n1−1)S1²+(n2−1)S2²]/(n1+n2−2). t=(Xbar1−Xbar2)/(Sp√(1/n1+1/n2)),dfn1+n2−2. BetweenSS=(difference)²/(1/n1+1/n2),df1;divide bySp² gives t².',
'Independent normal samples have known variances4 and9,sizes16 and25. Give the exact test statistic for equal means and explain why the pooled equal-variance t argument is inapplicable.',
'Z=(Xbar1−Xbar2)/√(4/16+9/25)=(difference)/√.61,standard normal under null. Variances known and unequal;no common unknown variance justified for pooling.'],
[137,'Invert a parameter-free pivot while preserving inequality directions. Declare lower-tail versus upper-tail quantiles explicitly.',
'From iid normal data derive an equal-tailed1−α confidence interval forσ² using lower-tail χ²ν quantiles,ν=n−1. Explain the reversal.',
'P(qν(α/2)≤νS²/σ²≤qν(1−α/2))=1−α. All positive,so interval[νS²/qν(1−α/2),νS²/qν(α/2)]. Division reverses endpoint order.',
'For iid Exp(rateλ),use2λΣXi~χ²(2n) to derive an exact1−α equal-tail interval forλ.',
'[q_(2n)(α/2)/(2ΣXi),q_(2n)(1−α/2)/(2ΣXi)]. Hereλ multiplies the positive sample sum,so no reciprocal endpoint reversal.'],
[138,'Parameter intervals describe uncertainty in a fixed model parameter. A prediction interval also includes fresh-observation variability, even with the same fitted mean.',
'For iid normal sample size n≥2,derive a1−α interval forμ and a prediction interval for an independent future observation Xnew.',
'Mean Xbar±t_(n−1)(1−α/2)S/√n. Future Xnew−Xbar normal varianceσ²(1+1/n),independent ofS;prediction Xbar±t S√(1+1/n).',
'For iid uniform(0,θ),maximumM,derive an exact one-sided1−α upper confidence bound forθ. State its coverage event.',
'UM=M/α^(1/n). θ≤UM iffM/θ≥α^(1/n),probability1−α since CDF ofM/θ is u^n. Bound exceeds or equalsM;it concernsθ,not a future draw.'],
[139,'A CLT interval is asymptotic unless an exact pivot is available. Keep the sample-size and interior-parameter assumptions visible.',
'For Bernoulli data with0<p<1,derive the usual Wald1−α interval and explain its approximation and range issue.',
'phat±z_(1−α/2)√[phat(1−phat)/n],from CLT and consistent plug-in. Approximate coverage asn→∞,not exact;endpoints may leave[0,1]. Simply clipping does not make the derivation exact.',
'For iid finite-variance data withσ²>0 and consistent sample variance,derive an asymptotic test of μ=μ0 and contrast it with exact normal-theory t inference.',
'√n(Xbar−μ0)/S⇒N(0,1),two-sidedz threshold asymptotic. Exact t law requires iid normal errors;finite variance alone gives no exact t distribution.'],
[140,'Boundary estimates can make a Wald standard error vanish even when substantial uncertainty remains. Exact discrete inversion can provide a useful one-sided bound.',
'Observe zero successes in n=10 Bernoulli trials. Explain the Wald interval failure and derive the exact one-sided upper bound obtained fromPp(X=0)=α.',
'phat0 gives Wald interval[0,0],which is misleading for positivep. (1−p)^10=α gives upper1−α^(1/10). This is the zero-success endpoint of an exact binomial inversion procedure;other observations need their own endpoints.',
'If iid observations have Cauchy locationθ,may the finite-variance CLT justify a standard sample-mean z interval? Explain without assuming a mean exists.',
'No:ordinary Cauchy expectation and variance do not exist,so hypotheses fail. Failure of this theorem is not itself a proof of every alternative procedure;the stated z derivation is unjustified.'],
[141,'A sign test targets a median via sign probabilities. Ties at the reference value change the effective experiment and require an explicit convention and null model.',
'For iid continuous observations under a null median m0 withP(X>m0)=P(X<m0)=1/2,derive the law of the number above m0. What should be checked before dropping zeros in rounded data?',
'Signs iid Bernoulli1/2,so countBin(n,.5). With zeros,dropping them is exact conditional on nonzero count only if nonzero signs remain iid balanced under the specified null;mere median membership with atoms need not ensure this.',
'Differences are−2,0,3,1,−1,4. Under a null model granting independent balanced nonzero signs,drop zeros,find effective n and the upper-tail p-value.',
'Five nonzero signs,three positive. P(Bin(5,.5)≥3)=1/2. The balance assumption must be stated,not inferred from the deletion.'],
[142,'Exact binomial critical regions have attainable sizes; equal-tailed nonrandomized tests may be conservative. Include boundaries and any randomization explicitly.',
'For six independent balanced signs,consider a two-sided rule rejecting if all signs agree. Find exact size and its power when positive probability is.3.',
'Size2/64=1/32. Power(.3)^6+(.7)^6=.118378. It is conservative relative to nominal.05.',
'For n=5 signs,construct an upper-tail nonrandomized test with size≤.05 and explain why adding the next integer count violates that level.',
'Reject only S=5,size1/32=.03125. IncludingS=4 raises size(5+1)/32=.1875. Randomization could use part of the boundary mass if exact.05 were required.']
];
