export default [
[101, 'Linear forms of a jointly normal vector remain jointly normal. Zero covariance then implies independence; that implication is not valid for arbitrary distributions.',
'Let X, Y independent N(0, 1). For U=X+Y, V=X−Y find joint normal parameters and decide independence. Explain precisely where normality enters.',
'Means0, variances2, covarianceVarX−VarY=0. The linear transform is jointly normal; diagonal covariance makes the joint law a product. Zero covariance alone would not suffice.',
'Let jointly normal X, Y have variances4, 9 and covariance3. Find Cov(X+Y, 2X−Y) and decide independence of these two forms.',
'Cov=2·4−9+(2−1)·3=2≠0, so not independent. Variances of forms19 and13 respectively.'],
[102, 'For nonsingular bivariate normal data, conditional mean is affine and conditional variance is constant. Perfect correlation produces a degenerate conditional law.',
'Jointly normal X, Y have means1, 2, variances4, 9, covariance3. Derive Y|X=x, then give E(Y|X=3) and conditional variance.',
'Coefficient3/4; residual Y−2−(3/4)(X−1) has covariance0 with X and normal variance9−9/4=27/4. Conditional mean2+.75(x−1), at3 equals3.5; variance27/4.',
'Let X~N(0, 1), Y=2X+1. Describe Y|X=x and explain why an ordinary two-dimensional density formula is invalid.',
'Point mass at2x+1, conditional variance0. Joint law lies on a line and covariance determinant0, so no nonsingular bivariate Lebesgue density.'],
[103, 'An orthogonal transform of independent standard normals preserves the standard joint normal law. Use one coordinate for the mean and the rest for residuals.',
'For iid Xi~N(μ, σ²), n≥2, show Xbar is independent of the residual vector and derive the law of Σ(Xi−Xbar)²/σ².',
'Choose orthonormal first vector1/√n, complete to basis. Standardized coordinates independent N(0, 1); first is√n(Xbar−μ)/σ, residual coordinates remaining n−1. Residual squared norm is χ²(n−1) and independent of first.',
'For independent X1, X2~N(μ, σ²), find laws and independence of (X1+X2)/2 and X1−X2. Does uncorrelatedness alone extend the result to arbitrary iid data?',
'Mean N(μ, σ²/2), differenceN(0, 2σ²), covariance0 and jointly normal, so independent. Arbitrary iid data only guarantees covariance0; Bernoulli data give dependent mean/difference.'],
[104, 'A t ratio needs a standard normal numerator independent of a scaled chi-square denominator. Degrees of freedom and independence are part of the pivot, not decorations.',
'For iid normal sample size n≥2 with sample variance S², derive the law of √n(Xbar−μ)/S. For two independent normal samples give the law of their variance ratio under equal population variances.',
'Normal numerator Z independent of V=(n−1)S²/σ²~χ²(n−1), so ratio t(n−1). Under equal variance, S1²/S2²~F(n1−1, n2−1), requiring independent samples.',
'Let Z~N(0, 1) and V=Z². Is Z/√V a t variable with1 degree of freedom? Explain.',
'Ratio=signZ almost surely, with masses1/2 at±1. Although V~χ²1, it is not independent of Z, so t construction fails.'],
[105, 'For independent observations a maximum CDF multiplies individual CDFs; a minimum survival multiplies survivals. Distinguish ≤ from > when atoms exist.',
'For iid Xi with continuous CDF F, derive maximum and minimum CDFs. Specialize to iid uniform(0, 1), n≥1.',
'Fmax(t)=F(t)^n, Fmin(t)=1−[1−F(t)]^n. On0<t<1 uniform gives t^n and1−(1−t)^n, with0/1 extensions outside.',
'For independent exponential ratesλ1, ..., λn, find the minimum distribution and its mean.',
'Survival product exp(−tΣλi), t≥0; minimumExp(rateΣλi), mean1/Σλi.'],
[106, 'Extreme laws extend to nonidentical distributions by products, but iid powers then become invalid. Discrete extremes retain point masses.',
'For n iid uniform(0, θ), θ>0, find E M and VarM for their maximum M.',
'Density n m^(n−1)/θ^n on(0, θ). E M=nθ/(n+1), E M²=nθ²/(n+2), variance nθ²/[(n+1)²(n+2)].',
'Two independent fair dice have maximum M. Find its PMF and mean.',
'P(M≤k)=k²/36, k1, ..., 6; mass(2k−1)/36. MeanΣk(2k−1)/36=161/36.'],
[107, 'The kth order statistic is below a threshold exactly when at least k observations are below that threshold. Translate the event before applying a binomial count.',
'For n iid continuous observations with CDF F, derive P(X_(k)≤t). For n=5, k=3, F(t)=.5 compute it.',
'Count N=Σ1{Xi≤t}~Bin(n, F(t)); probabilityΣ(j=k to n)C(n, j)F(t)^j[1−F(t)]^(n−j). Symmetry for Bin(5, .5) gives1/2.',
'For four iid uniform(0, 1), find P(X_(2)>.5) by an event-count argument.',
'At most1 observation≤.5. Probability(1+4)/16=5/16; strict versus weak threshold irrelevant here by continuity.'],
[108, 'Differentiating the binomial-tail CDF yields the order-density coefficient. Check k=1 and k=n against the extreme formulas.',
'Derive the density of X_(k) for iid continuous density f, CDF F. Specialize to uniform(0, 1), and state endpoint cases.',
'Density n!/[(k−1)!(n−k)!] F^(k−1)(1−F)^(n−k)f. This is Beta(k, n+1−k) for uniforms. k1 gives n(1−F)^(n−1)f; kn gives nF^(n−1)f.',
'Find the mean of the median from five iid uniforms by direct integration of its density.',
'Density30x²(1−x)² on(0, 1). Mean30(1/4−2/5+1/6)=1/2; density integrates1.'],
[109, 'Joint order statistics require allocation of observations to disjoint intervals. Marginal or conditional laws must respect the triangular ordering support.',
'For n≥2 iid uniforms(0, 1), derive the joint density of minimum U and maximum V and the density of range R=V−U.',
'Joint n(n−1)(v−u)^(n−2), 0<u<v<1. Integrate u from0 to1−r gives fR(r)=n(n−1)r^(n−2)(1−r), 0<r<1.',
'For three iid uniforms, find the conditional law of the minimum given maximum v, using densities, and its conditional expectation.',
'Joint6(v−u), marginalmaximum3v²; conditional2(v−u)/v² on(0, v), mean v/3.'],
[110, 'A shared observation can create positive probability along a diagonal even with continuous marginals. A diagonal component is not a point atom at a fixed coordinate.',
'For independent uniform(0, 1) X1, X2, X3, let U=max(X1, X2), V=max(X2, X3). Derive joint CDF, probability U=V, and describe the off-diagonal density and diagonal mass.',
'CDF uv min(u, v) for0≤u, v≤1, extended appropriately. Equality occurs when X2 is largest, probability1/3. Density2u foru<v, 2v forv<u, total2/3. Diagonal measure P(U=V∈dt)=t²dt, total1/3; no fixed joint point has positive mass.',
'For the same construction with minima instead of maxima, find P(U=V) and diagonal measure. Is an ordinary joint density alone sufficient?',
'Equality iff shared X2 is smallest, probability1/3. Diagonal density with respect to dt is(1−t)² on(0, 1). Positive mass on a planar zero-area set prevents a density-only representation.'],
[111, 'Markov requires a nonnegative variable and positive threshold; Chebyshev requires finite variance. A bound greater than1 is valid but uninformative.',
'If X≥0, EX=3, derive P(X≥10)≤.3. If EY=2, VarY=4, derive a bound on P(|Y−2|≥5), stating every assumption.',
'10·1{X≥10}≤X; expectations give.3. Apply Markov to(Y−2)² at25 to obtain4/25. Nonnegativity applies to the squared variable.',
'Can Markov be applied directly to an arbitrary signed Z knowing EZ=0 to conclude P(Z≥1)=0? Give a counterexample and a valid alternative with a second moment.',
'No:Z=±1 equally has mean0 but tail1/2. If EZ²<∞, P(|Z|≥a)≤EZ²/a² by Markov on Z².'],
[112, 'For independent observations finite variance gives a Chebyshev sample-size guarantee. It is a distribution-free bound, often more conservative than a normal approximation.',
'For iid meanμ, variance9, find an n ensuring P(|Xbar−μ|≥.5)≤.05 by Chebyshev. State whether the bound is exact.',
'Bound9/(n·.25)=36/n. n≥720 suffices. It is an upper bound, not generally the actual probability.',
'If Var Xbar=1/n+.2, what can Chebyshev guarantee about P(|Xbar−EXbar|≥1) as n grows? Can it certify a.05 bound?',
'Upper bound1/n+.2, clipped at1 if needed. It approaches.2 and never certifies.05. Failure of this bound does not alone prove the actual tail exceeds.05.'],
[113, 'WLLN gives convergence in probability of iid averages under its stated integrability assumptions. A proof via Chebyshev uses the stronger finite-variance condition.',
'For iid Xi with meanμ and finite varianceσ², prove Xbar→μ in probability. Then prove aXbar+b consistently estimates aμ+b for fixed a, b.',
'Chebyshev boundσ²/(nε²)→0. For a≠0 use thresholdε/|a|; a=0 is exact. This establishes convergence in probability, not almost-sure convergence by this argument.',
'For iid Bernoulli(p), prove the sample proportion consistently estimates p and derive a uniform-in-p Chebyshev bound.',
'Variancep(1−p)/n≤1/(4n). Tail≤1/(4nε²) uniformly forp∈[0, 1].'],
[114, 'Consistency is a probability statement. Vanishing MSE is sufficient; nonvanishing moments alone are not a general inconsistency proof without extra conditions.',
'Let iid Xi have meanμ, varianceσ² and Tn=Σ(i=1 to n)(Xi+X(i+1))/(2n). Prove consistency. Contrast Yn=μ+Z for a common fair sign Z.',
'ETn=μ, variance(4n−2)σ²/(4n²)→0; Chebyshev. For Yn, P(|Yn−μ|>.5)=1 for every n, so inconsistent, established by a nonvanishing tail.',
'Let En=n with probability1/n and0 otherwise. Determine convergence in probability to0, mean and variance. What does this show about moment-based refutations?',
'For fixedε>0, n>ε, tail1/n→0. Mean1, secondmomentn, variance n−1. Nonvanishing bias or variance does not alone refute convergence in probability.'],
[115, 'CLT centers by the true mean and scales by the square root of variance. It is an approximation at finite n; continuity correction can improve integer-count approximations.',
'For iid mean10, variance4, approximate P(Σ(i=1 to100)Xi>1020) by CLT and state assumptions and limitation.',
'Standardization(1020−1000)/(2√100)=1 gives1−Φ(1). iid finite nonzero variance; the probability is approximate with no finite-sample error bound supplied.',
'Approximate P(X≥60) for X~Bin(100, .5), including continuity correction.',
'Mean50, SD5. Threshold59.5 gives1−Φ(1.9). Without correction1−Φ(2); neither is the exact binomial tail.'],
[116, 'Group dependent observations into independent blocks when justified. Replacing an unknown scale by a consistent estimator requires a convergence argument, not simply a substitution.',
'Let iid Xi have meanμ, varianceσ²>0. Set Yi=X(2i−1)+X(2i). State a CLT for the average of m blocks and relate it to the original2m-observation average.',
'Yi iid mean2μ, variance2σ². √m(Ybar−2μ)/(√2σ)⇒N(0, 1). Original meanYbar/2 gives√(2m)(Xbar−μ)/σ⇒N(0, 1).',
'For iid Bernoulli(p), 0<p<1, justify √n(phat−p)/√[phat(1−phat)]⇒N(0, 1). Address a zero denominator at finite n.',
'CLT with true variance; WLLN and continuity give plug-in variance→p(1−p)>0; Slutsky gives result. Finite all-equal samples cause zero denominator and require a separately defined statistic; their probability p^n+(1−p)^n→0.'],
[117, 'A quantile event is an empirical-count event with a carefully chosen strict or weak inequality. For discontinuous laws, F(t−) and F(t) differ.',
'For iid continuous F and k=ceil(np), express events X_(k)≤a and X_(k)>b using empirical counts. State the binomial parameters.',
'First {Σ1{Xi≤a}≥k}, countBin(n, F(a)). Second {Σ1{Xi≤b}≤k−1}, countBin(n, F(b)). Continuity permits ignoring equalities at fixed thresholds.',
'Without continuity, express X_(k)<a and X_(k)≥a using a count and give its success probability.',
'Use N_< =Σ1{Xi<a}, parameterF(a−). Events N_<≥k and N_<≤k−1 respectively; replacing F(a−) byF(a) can be wrong at atoms.'],
[118, 'Consistency of a sample quantile needs strict CDF separation around the target. A flat region can prevent concentration at a nominated point.',
'Let k_n/n→p∈(0, 1). Suppose for every ε>0, F(q−ε)<p<F(q+ε). Prove X_(k_n)→q in probability using WLLN on counts.',
'For lower tail, empirical fraction atq−ε converges toF(q−ε)<p while thresholdk_n/n→p, so probability of fraction≥threshold→0. Upper tail similarly usesF(q+ε)>p. Union bounds the two tails.',
'Let X be0 or2 with probability1/2 each. Can every point q∈[0, 2] be a probability limit of the lower sample median X_(ceil(n/2))? Explain using q=1.',
'No. Every sample median is0 or2, so P(|median−1|>.5)=1. Population median nonuniqueness alone does not imply consistency at an arbitrary chosen median; strict separation fails around1.']
];
