export default [
[81,'A CDF is nondecreasing, right-continuous and has limits0 and1. A jump is a point mass; a density value at a point is not a probability.',
'Let F(x)=0 for x<0,(1+x)/2 for0≤x<1,and1 for x≥1. Verify the CDF conditions, find all atoms and a density for its continuous part, and compute P(0<X≤1/2).',
'Right-continuous and nondecreasing with proper limits. Jump1/2 at0,none at1. Continuous part density1/2 on(0,1),total mass1/2. Requested probability F(1/2)−F(0)=3/4−1/2=1/4.',
'For X uniform(0,1), is P(X=1/2) equal to its density value1? Give the CDF and calculate P(1/4<X≤3/4).',
'Point probability0,not1. CDF0 below0,x on[0,1],1 above1. Interval probability1/2.'],
[82,'A mixed law can have both atoms and a continuous part. Transform probability events to find the CDF, including jumps and endpoint conventions.',
'Let U uniform(−1,2) and Y=min(1,max(0,U)). Give the CDF, all atoms, continuous density and EY.',
'Atoms0 and1 each mass1/3. CDF0 below0,(y+1)/3 on0≤y<1,1 at/above1. Density1/3 on(0,1); EY=1/3+∫₀¹y/3dy=1/2.',
'X has P(X=0)=1/4 and, otherwise, is uniform(0,2). Find the CDF of Y=−X, its atoms and continuous density.',
'Y atom0 mass1/4. CDF0 for y<−2,3(y+2)/8 for−2≤y<0,1 for y≥0. Density3/8 on(−2,0). Left limit at0=3/4 differs from value1.'],
[83,'Uniform probabilities are length ratios; exponential distributions need an explicit rate or scale convention. Memorylessness is an event identity.',
'For U uniform(2,6) find P(U>5),EU,VarU. For X exponential with rate2 find P(X>3|X>1),EX and VarX.',
'Uniform1/4,mean4,variance16/12=4/3. Exponential survival e^−2x;conditional survival e^−4,mean1/2,variance1/4.',
'For exponential rateλ>0 compute E(X²) directly by integration and determine P(X≤EX).',
'Two integrations by parts give E X²=2/λ². P(X≤1/λ)=1−e^−1,independent of λ.'],
[84,'Standardize a normal variable by subtracting its mean and dividing by its standard deviation. Central and raw moments differ.',
'If X~N(3,4), express P(1<X<7) using the standard normal CDF Φ. Compute E X² and E(X−3)^4.',
'Standard deviation2; probabilityΦ(2)−Φ(−1). Raw second moment4+9=13. Fourth central moment3·2⁴=48.',
'For Z standard normal derive EZ⁴=3 by integration by parts from density φ, using φ′=−zφ and EZ²=1. Compute E(2+Z)^3.',
'Integrate−∫z³φ′=3∫z²φ=3,with vanishing boundary. Expansion gives8+6EZ²=14 since odd standard-normal moments vanish.'],
[85,'Moment existence is an endpoint question. State shape and rate/scale conventions before applying gamma or beta identities.',
'For X~Gamma(shape α>0,rate λ>0), derive E X^p for real p and its exact existence range. Use the gamma integral definition.',
'E X^p=λ^−p Γ(α+p)/Γ(α),finite iff α+p>0; the exponential tail handles∞,near0 integrability requires exponentα+p−1>−1.',
'For U~Beta(a,b),a,b>0,derive E[U^r(1−U)^s] and the exact conditions on real r,s.',
'Integral ratio B(a+r,b+s)/B(a,b),finite iff a+r>0 and b+s>0. Equality at either boundary gives logarithmic divergence.'],
[86,'An MGF must be finite in a neighborhood of zero to invoke its standard uniqueness theorem. Products represent sums only with independence.',
'For independent Xi~Exp(rateλ),i=1,...,n,derive the MGF of their sum, its existence interval and the resulting law.',
'MXi(t)=λ/(λ−t),t<λ. Product[λ/(λ−t)]^n identifies Gamma(shape n,rateλ). At t≥λ the integral diverges.',
'Independent X~Poisson(λ),Y~Poisson(μ). Find the MGF of2X+Y and decide whether it is Poisson when λ>0.',
'M(t)=exp[λ(e^(2t)−1)+μ(e^t−1)],all real t. Mean2λ+μ,variance4λ+μ differ when λ>0,so not Poisson.'],
[87,'For many-to-one transformations add contributions from every inverse branch. The support is the image of the original support, with endpoint atoms checked separately.',
'X is uniform(−2,1),Y=X². Derive FY and a density, accounting for both branches and the support.',
'FY=0 below0;2√y/3 for0≤y≤1;(1+√y)/3 for1≤y≤4;1 above4. Density1/(3√y) on(0,1),1/(6√y) on(1,4). No atoms.',
'X~Exp(rate1),Y=e^−X. Find its law by the CDF, not by guessing.',
'For0<y<1,P(Y≤y)=P(X≥−logy)=y. Thus uniform(0,1),with no endpoint atoms.'],
[88,'Rounding partitions the original support into cells; censoring can collect a whole interval into an atom. Neither generally preserves a continuous density-only law.',
'X~Exp(rateλ),K=floor X. Derive its PMF and identify a standard discrete law with its convention.',
'P(K=k)=e^−λk−e^−λ(k+1)=(1−e^−λ)e^−λk,k≥0. Geometric failures-before-success with p=1−e^−λ.',
'For X~Exp(rate1),Y=min(X,c),c>0,find atoms,continuous density and EY.',
'Densitye^−y on(0,c),atom at c of mass e^−c. EY=∫₀^cP(X>t)dt=1−e^−c,also by adding atom contribution to integral.'],
[89,'For signed expectations existence requires the relevant positive and negative parts, not a symmetric principal-value cancellation. Absolute powers can also fail locally at zero.',
'For standard Cauchy density1/[π(1+x²)],determine all real p for which E|X|^p is finite. Decide whether EX and the MGF at any t≠0 exist.',
'Near0 requires p>−1;tails require p<1. Thus−1<p<1. EX is undefined because both positive and negative parts diverge; symmetric principal value0 is not expectation. For t>0 positive tail exponential divergence;for t<0 negative tail,so MGF infinite at every nonzero t.',
'For a density proportional to1/(1+|x|³) on R determine the finite absolute-moment range and whether mean and variance exist. Normalizing constant need not be computed.',
'Near0 requires p>−1;tail integrand comparable |x|^(p−3),so p<2. Range(−1,2). First absolute moment finite,symmetric mean0;second diverges,so no finite variance.'],
[90,'For an unfamiliar density first normalize and identify support. Piecewise tails can determine moments and the MGF interval without needing a named distribution.',
'Let f(x)=c e^−|x|/b on R,b>0. Find c,mean,variance and the MGF with its existence interval.',
'Integral2b gives c=1/(2b). Symmetry and integrability give mean0;second moment2b². Split integral gives M(t)=1/(1−b²t²) for|t|<1/b,diverges at/outside endpoints.',
'Density f(x)=c x on0<x<2. Normalize and find E X,VarX and P(X>1).',
'c=1/2. EX=(1/2)∫₀²x²=4/3,EX²=2,variance2/9. Tail integral3/4.'],
[91,'Marginalize only over the legal joint support. A rectangular-looking formula does not override a triangular or constrained support.',
'Joint density is c on0<x<y<1 and0 otherwise. Find c,both marginal densities,EX and EY.',
'Area1/2 gives c2. fX(x)=2(1−x),fY(y)=2y on(0,1). EX=1/3,EY=2/3.',
'On x,y∈{0,1},joint masses in order00,01,10,11 are.1,.2,.3,.4. Find both marginals and E(XY).',
'P(X=1)=.7,P(Y=1)=.6;zero masses.3,.4. Product XY is1 only at11,so expectation.4.'],
[92,'Conditional densities divide the joint by a positive marginal and inherit the conditional support. Independence requires a product law over the full support.',
'For joint density2 on0<x<y<1,derive X|Y=y and test independence.',
'fY=2y;conditional fX|Y=1/y on(0,y),uniform(0,y),for y∈(0,1). Support depends on y and joint cannot equal positive marginal product on the whole unit square,so dependent.',
'For the four masses(.1,.2,.3,.4) on00,01,10,11,find P(X=1|Y=1) and test independence. Contrast with masses(.12,.18,.28,.42).',
'First conditional.4/.6=2/3≠.7,dependent. Second marginals X1=.7,Y1=.6;all cells factor,so independent.'],
[93,'Conditional expectation averages the conditional model, then averages over the conditioning information. Choose information that simplifies the experiment.',
'N~Poisson(λ). Given N,let S be the sum of N iid payoffs independent of N,each integrable with meanμ,empty sum0. Find ES with justification.',
'E(S|N)=Nμ;iterated expectation gives ES=λμ. Absolute integrability follows EΣ|payoff|=λE|payoff|<∞.',
'Choose P uniformly on(0,1),then X|P~Bin(n,P). Find EX and P(X=n).',
'EX=E(nP)=n/2. P(X=n)=E P^n=1/(n+1).'],
[94,'Total variance separates average conditional variance from variation of conditional means. The second term is easy to lose in a mixture.',
'For P uniform(0,1) and X|P~Bin(n,P),derive VarX.',
'E Var(X|P)=nE[P(1−P)]=n/6. Var E(X|P)=n²VarP=n²/12. Sum n(n+2)/12.',
'For the random sum S with N~Poisson(λ),payoff meanμ,varianceσ² and independent iid payoffs,derive VarS.',
'Conditional variance Nσ²,conditional mean Nμ. Total varianceλσ²+λμ². Requires finite payoff second moment.'],
[95,'Convolution integrates over where both summands are legal. A ratio can be simpler from a probability region than from a memorized formula.',
'For independent uniform(0,1) X,Y derive the density of S=X+Y,including its support.',
'Convolution length of(0,1)∩(s−1,s):fS=s for0<s<1,2−s for1≤s<2,0 otherwise.',
'For independent Exp(rate1) X,Y,find the CDF and density of R=X/Y.',
'For r≥0,P(X≤rY)=∫₀∞(1−e^−ry)e^−y dy=r/(1+r). Density1/(1+r)² for r>0;CDF0 for r<0.'],
[96,'A Jacobian formula is branchwise. Establish an inverse and transformed support before taking the absolute determinant; sum separate branches when needed.',
'For independent Exp(rate1) X,Y define U=X+Y,V=X/(X+Y). Find joint density and decide independence.',
'Inverse x=uv,y=u(1−v),support u>0,0<v<1,absolute Jacobian u. Jointu e^−u,product Gamma(2,1) density and uniform(0,1),so independent.',
'For X uniform(−1,1),Y uniform(0,1) independent,transform U=X²,V=Y. Show all branches and find joint density.',
'Branches x=±√u,y=v each contribute original density1/2 times1/(2√u). Sum1/(2√u),0<u,v<1. Product support/density gives independence.'],
[97,'Squared loss is minimized by the mean when the second moment exists. Absolute loss is minimized by every median; the minimizer may be an interval.',
'For data0,1,4,9 find all real a minimizing Σ(xi−a)² and all minimizing Σ|xi−a|. Prove both conclusions.',
'Squares complete to constant+4(a−3.5)²,unique mean3.5. Absolute loss has zero slope between middle values1,4 and slopes pointing toward that interval outside;all a∈[1,4].',
'For masses.2,.3,.5 at0,2,10,find squared- and absolute-loss minimizers.',
'Mean0+.6+5=5.6 is unique squared minimizer. Median condition P(X≤a)≥.5 andP(X≥a)≥.5 holds for all a∈[2,10],the absolute minimizers.'],
[98,'Weighted absolute loss is minimized by weighted medians after transforming the parameter correctly. A reciprocal parameter may restrict or reverse the transformed domain.',
'Find all b>0 minimizing |1/b−1|+|1/b−2|+|1/b−3|+|1/b−5|.',
'Let z=1/b>0. Median interval z∈[2,3]. Invert monotonically decreasing: b∈[1/3,1/2].',
'Find all a minimizing2|a|+|a−2|+|a−5|. Then minimize |1/b|+|1/b−2| over b>0.',
'Weights total4,half2. All a∈[0,2] minimize first. Second in z=1/b>0 has medians[0,2] intersect(0,∞)=(0,2];thus b∈[1/2,∞),with no finite b representing z0.'],
[99,'First-step equations require states recording the information relevant to future waiting. An algebraic solution must correspond to a finite expected hitting time.',
'For fair coin tosses find the expected number of tosses until HH first occurs, using explicit states and justifying finiteness.',
'Let E0 no trailingH,E1 trailingH. E0=1+(E0+E1)/2;E1=1+E0/2. Solve E0=6,E1=4. Disjoint two-toss blocks succeed with probability1/4,so waiting is bounded by twice a geometric wait,finite.',
'For independent trials with success p∈(0,1),derive expected time until two consecutive successes.',
'E0=1+(1−p)E0+pE1;E1=1+(1−p)E0. Solve E0=(1+p)/p². Disjoint success-pair blocks provide finite expectation bound2/p².'],
[100,'A stopping event may alter the conditional law of all previous observations. Recompute event masses instead of reusing an unconditional waiting formula.',
'Roll a fair die until the first6 at time T. Given every earlier roll was odd,find the conditional law of T and ET under that conditioning.',
'Joint probability T=t and condition is(3/6)^(t−1)(1/6). Sum over t gives1/3. Conditional mass2^−t,t≥1,geometric with success1/2,mean2.',
'Toss a fair coin until a toss differs from the first toss. Find expected stopping time including the initial toss,by conditioning on the first result.',
'After the first toss,each further toss differs with probability1/2 independently. Additional waiting geometric trials mean2,so total mean3. Conditional on either first outcome same result.']
];
