export default [
[143,'Least squares comes from minimizing the stated sum of squared residuals. Omitting an intercept changes both normal equations and residual identities.',
'Fit y=a+bx to(0,1),(1,2),(2,2) by deriving normal equations. Give fitted coefficients and residuals.',
'EquationsΣ(y−a−bx)=0 andΣx(y−a−bx)=0. xbar1,ybar5/3,Sxx2,Sxy1; b1/2,a7/6. Residuals−1/6,1/3,−1/6.',
'Fit y=bx through the origin to the same data. Find b,residuals,and check whether their sum must vanish.',
'b=Σxy/Σx²=6/5. Residuals1,4/5,−2/5 sum7/5≠0. OnlyΣx residual=0 is enforced;no intercept equation.'],
[144,'Residuals are orthogonal to the columns actually included in the design. A dummy variable can make a normal equation into a group-specific residual identity.',
'In full-rank least squares with an intercept and a group indicator D,prove the residual sum in each of the two groups is zero,even if other predictors are present.',
'Intercept column givesΣei=0;indicator givesΣDi ei=0 for group1. Subtraction gives group0 sum0. Assumes an ordinary unconstrained least-squares fit.',
'In a simple regression with intercept,replace every response yi by yi+c. Determine changes in intercept,slope,fitted values and residuals.',
'Sxy unchanged since centered responses unchanged;slope unchanged. Intercept increasesc,fitted values increasec,residuals unchanged.'],
[145,'With fixed full-rank design and homoscedastic uncorrelated errors, coefficient covariance isσ²(X^T X)^−1. Omitted-variable bias depends on alignment with the retained design.',
'For simple regression with intercept and fixed nonconstant x,derive Var(bhat),Var(ahat),Cov(ahat,bhat) under mean-zero independent varianceσ² errors.',
'bhat=b+Σ(xi−xbar)εi/Sxx. Varb=σ²/Sxx;ahat=a+εbar−xbar(bhat−b);Cov(εbar,bhat)=0. Vara=σ²(1/n+xbar²/Sxx),Cov=−σ²xbar/Sxx.',
'True model y=a+bx+cz+ε with Eε=0 and fixed predictors. Fit only intercept and x. Derive E(bhat) and a condition for no omitted-variable bias.',
'E bhat=b+cΣ(xi−xbar)(zi−zbar)/Sxx. No bias if c=0 or centered x,z orthogonal (assumingSxx>0).'],
[146,'A singular design may still identify some linear combinations. A linear estimand is identifiable exactly when it is unchanged along every null direction of the design.',
'In yi=α+β+εi,which linear combinations c1α+c2β are identifiable? Construct an unbiased estimator of every identifiable combination.',
'Null directions(t,−t);invariance requiresc1=c2=c. Estimandc(α+β),estimated byc ybar. Separateα,β not identifiable.',
'Let design columns be x and2x,with x nonzero. Identify the estimable coefficient combination and proveβ1 alone is not identifiable.',
'Mean vectorx(β1+2β2),soγ=β1+2β2 identifiable,estimated(x^T y)/(x^T x). Shift(β1,β2)→(β1−2t,β2+t) leaves law unchanged under same errors but changesβ1.'],
[147,'Exact regression t and F laws require a normal homoscedastic error model with the stated rank. Nested-model differences use the difference in ranks, not raw column counts.',
'For y=Xβ+ε,ε~N(0,σ²I),rankX=p<n,derive the t statistic for H0:c^Tβ=d and its degrees of freedom.',
'βhat=(X^TX)^−1X^Ty;normal numerator varianceσ²c^T(X^TX)^−1c. s²=SSE/(n−p) independent of fitted coordinates. t=(c^Tβhat−d)/(s√[c^T(X^TX)^−1c])~t(n−p) fornonzero contrast.',
'A reduced model rank2 and nested full model rank4 fit n=20 observations with SSEr=50,SSEf=30. Compute the exact-model F statistic and degrees of freedom.',
'F=[(50−30)/(4−2)]/[30/(20−4)]=16/3,df(2,16). Exact null F needs normal independent common-variance errors and correct reduced mean model.'],
[148,'A fitted mean and a future observation have different variance. Prediction adds fresh error variance,not just uncertainty in the estimated coefficient.',
'For simple normal regression with intercept,derive intervals at x0 for the mean response and a new independent response,using n>2.',
'h0=1/n+(x0−xbar)²/Sxx. Mean interval yhat0±t_(n−2)(1−α/2)s√h0;prediction uses√(1+h0). Same normal model and independent future error required.',
'For n=10,x0=xbar,s=2,compare the two standard errors numerically and explain why the prediction interval remains wide as n grows.',
'Mean SE2/√10;prediction SE2√1.1. At mean design point,mean uncertainty vanishes withn but fresh observation varianceσ² remains.'],
[149,'Design-based sampling treats finite population values as fixed. State whether S² uses N−1 or N before applying a finite-population correction.',
'For population1,2,4,5,sample size2,find population mean,S² with denominatorN−1,and variance of sample mean under SRSWR and SRSWOR. Give total-estimator variances.',
'Mean3,sum squared deviations10,S²10/3. WR variance[(N−1)/N]S²/n=5/4;WOR(1−n/N)S²/n=5/6. Total N ybar variances multiply16:20 and40/3.',
'Derive Var(ybar) for SRSWOR using Cov of two distinct draws and check the census limit.',
'Each draw varianceσN²=(N−1)S²/N;distinct-drawcov=−σN²/(N−1)=−S²/N. Sum gives(1−n/N)S²/n. At n=N variance0.'],
[150,'SRSWOR makes every subset of a fixed size equally likely. Equal first-order inclusion probabilities alone do not prove the stronger property.',
'Uniformly permute N labels and take the first n as an unordered sample. Prove this is SRSWOR by counting permutations for each subset.',
'Each n-subset occupies the first n slots in n! ways and remaining slots in(N−n)! ways. Probability n!(N−n)!/N!=1/C(N,n).',
'From{1,2,3,4},choose uniformly one of{1,2},{2,3},{3,4},{4,1}. Compute inclusion probabilities and decide whether this is SRSWOR of size2.',
'Each unit appears in2/4 samples,πi1/2. Only4 of6 subsets possible,so not SRSWOR despite equal inclusions.'],
[151,'Stratified means use population-share weights. Independent within-stratum sampling adds weighted variances with a separate finite-population correction in each stratum.',
'Strata sizes40,60 have sample sizes4,6,means10,20 and known finite-population S² values4,9 (denominator Nh−1). Under independent SRSWOR find estimated mean,total,and design variances.',
'Weights.4,.6 give mean16,total1600. Varmean=.4²(.9)4/4+.6²(.9)9/6=.144+.486=.63. Vartotal100²·.63=6300.',
'Explain why unweighted averaging of the two stratum sample means is biased for the population mean when the population weights differ. Give the expectation discrepancy forμ1=10,μ2=20 andweights.4,.6.',
'Unweighted expectation15 versus target16,bias−1. Weighting by sample shares only agrees when allocation happens to match population shares.'],
[152,'Neyman allocation minimizes the variable part of design variance. Costs alter the square-root rule; continuous solutions must be checked against bounds and integer budgets.',
'Two strata have sizes100,200 and standard deviations2,1. For fixed total sample30 derive the variance-minimizing continuous allocation and check feasibility.',
'Variable partΣWh²Sh²/nh;Lagrange gives nh∝NhSh. Products200,200 give15,15,bothpositive and below stratum sizes.',
'For the same strata,costs1,4 per observation,budget60,derive the continuous optimal allocation. Explain what to do if a continuous result exceeds a stratum size.',
'nh∝NhSh/√ch,ratio200:100=2:1. Cost n1+4n2=60 gives20,10,feasible integers. If boundviolated,fix saturatedstratum atNh and optimize remaining budget;do not blindly round or exceed population.'],
[153,'First-order inclusion is probability of appearing at least once; joint inclusion concerns both distinct units. Neither is generally the same as a per-draw probability or a product.',
'For the four cyclic pairs on{1,2,3,4} chosen uniformly,find πi,πij for adjacent and opposite pairs,and indicator covariances.',
'πi1/2. Adjacent joint1/4,opposite0. Covadjacent0;Covopposite−1/4. Zero covariance for some pairs does not make all inclusion indicators mutually independent.',
'Draw twice independently and uniformly from N≥2 labels,then retain unique labels. Find probability a specified label is included and that two specified distinct labels are both included.',
'πi=1−(1−1/N)²=2/N−1/N². Both included only by two orders of those labels,πij=2/N². Distinct-sample size is random.'],
[154,'Horvitz–Thompson unbiasedness uses E Ii=πi and linearity,not independence. Positive inclusion probabilities are necessary to estimate an arbitrary total this way.',
'Under the four cyclic-pair design,population values are1,2,4,8. Compute the inverse-inclusion total estimate for each possible sample and verify unbiasedness by enumeration.',
'πi1/2;estimates2 times pair sums:6,12,24,18,average15=true total. Dependence of inclusion indicators does not impair the argument.',
'For any finite-population design withπi>0,prove Σ(sample)yi/πi unbiased for total and derive the corresponding mean estimator. What if one unit hasπi=0?',
'WriteΣIi yi/πi,expectationΣyi. Divide by knownN for mean. Ifπi0,the formula undefined and an arbitrary unseen unit value cannot be recovered unbiasedly from that design without extra model information.'],
[155,'A completely randomized design assigns treatments randomly among units. Under an additive model, total centered variation splits into between-treatment and within-treatment sums.',
'Two treatment groups have observations(1,2,3) and(3,4,5). Give the CRD model and compute grand mean,betweenSS,withinSS,totalSS and all degrees of freedom.',
'ModelYij=μ+τi+εij withidentifiabilityconstraint and randomizedassignment;normal independent equalvarianceerrors needed later for exactF. Grand3,groupmeans2,4. Between6,within4,total10;df1,4,5.',
'Prove the general identity SST=SSbetween+SSwithin using yi−grand=(yi−groupmean)+(groupmean−grand).',
'Expand squares;cross term for eachgroup containsΣ(yi−groupmean)=0. Thus SST=Σwithinresidual²+Σni(groupmean−grand)²,irrespective of normality.'],
[156,'The exact CRD F test uses residual MSE,not treatment or total MS. A pre-specified contrast has its own standard error under the same model.',
'For the two groups(1,2,3),(3,4,5),assuming independent normal common-variance errors,compute the treatment F and a t statistic for the mean difference.',
'MSE4/4=1;F=(6/1)/1=6,df1,4. Difference2,t=2/√(1/3+1/3)=√6,df4;its square equalsF.',
'For three groups of sizes4,5,6 and residualSSE30,construct a test statistic for contrastL=μ1−2μ2+μ3 using estimatedL=3. State degrees of freedom.',
'Error df15−3=12,MSE2.5. Variance estimate2.5(1/4+4/5+1/6)=73/24. t=3/√(73/24),df12 under normal equalvariance assumptions. Contrast coefficients sum0.'],
[157,'Blocking controls a nuisance source before treatment randomization. In a complete block, each treatment appears once and assignments are randomized separately within blocks.',
'Design an experiment with3 treatments and4 complete blocks. Describe valid randomization and the additive model; distinguish a block effect from a treatment effect.',
'Within each block independently permute the3 treatment labels over3 units. ModelYij=μ+τi+βj+εij,withzero-sumconstraints. Treatment is manipulated;block records nuisance grouping. Oneobs/cell does not separately estimate treatment-block interaction.',
'Why does assigning the same treatment to every unit in a block confound treatment with block in this design? Give the missing comparison.',
'Treatment then varies only between blocks,so treatment and block columns overlap;within-block treatment comparisons are absent. The ordinary complete-block additive treatment analysis is not supported.'],
[158,'RBD degrees of freedom are treatment t−1,block b−1,residual(t−1)(b−1). With one observation per cell,interaction cannot be separated from residual error.',
'Three blocks,each with two treatments,have rows(1,3),(2,5),(4,6). Compute the RBD ANOVA sums,df,MSE and treatmentF under the additive normal model.',
'Grand3.5,totalSS17.5. TreatmentSS49/6,blockSS9,residual1/3. df1,2,2,total5. MSE1/6,treatmentF49. Exact inference requires additive normal commonvariance errors.',
'For4 treatments and5 blocks,SST100,SStr30,SSblock50. Complete the table and explain what residualSS contains if interaction exists.',
'Residual20;df treatment3,block4,residual12,total19. MSE5/3,MS treatment10,F6. With oneobservation/cell interaction and error are inseparable;the additive-modelF may not have its claimed null law.'],
[159,'A Latin square places each treatment once in every row and column. Valid randomization permutes rows,columns and labels while preserving that constraint.',
'Construct a3×3 Latin square with treatmentsA,B,C. State the additive statistical model and a valid randomization procedure.',
'RowsABC,BCA,CAB work. ModelYij=μ+ri+cj+τ_(assignedij)+εij,withzero-sumconstraints. Randomly permute rows,columns and treatment labels;not arbitrary independent cell shuffling.',
'Is the array rowsAAB,BCC,CBA a Latin square? Diagnose it and explain why a visually balanced total treatment count is insufficient.',
'No:firstrow repeatsA;second repeatsC;third isdistinct but columns alsofail. Each treatment appearing3 times overall does not guarantee one perrow andcolumn.'],
[160,'Latin-square residual df is(p−1)(p−2). At p=2 it is zero,so there is no ordinary residual-MSE F test without additional information.',
'For a4×4 Latin square,SST120,SSrow20,SScolumn25,SStreatment45. Complete ANOVA and compute treatmentF with all assumptions.',
'Residual30. df total15,eachfactor3,residual6. MSE5,MStr15,F3 withdf3,6 under additive independent normal commonvariance errors and validrandomization.',
'Derive residual df for a p×p Latin square by counting independent additive parameters. Evaluate p=2 and state the implication for treatment testing.',
'Rank1+3(p−1)=3p−2;residualp²−(3p−2)=(p−1)(p−2). Atp2 zero,no residual variance estimate orordinaryF denominator. Replication or justified external error information is needed.'],
[161,'In a2² factorial,an effect is a difference of level averages. Coded-regression coefficients are half these effects when predictors use±1.',
'Cell means in order(--),(+-),(-+),(++) are1,3,5,11. Find grand mean,A,B,AB effects and coefficients inμ=β0+βA a+βB b+βAB ab.',
'Grand5. A effect(3+11−1−5)/2=4;B(5+11−1−3)/2=6;AB(1+11−3−5)/2=2. Coefficientsβ0=5,βA2,βB3,βAB1.',
'If cell means are2,4,5,7 in that order,compute interaction and explain its meaning as a difference of simple effects.',
'A simple effect2 at eachB level,difference0,ABeffect0. Equivalent contrast(2+7−4−5)/2=0. Additivity holds for these four means.'],
[162,'Replication supplies pure-error degrees of freedom. A saturated unreplicated factorial cannot manufacture residual error by algebra; pooling interactions adds an assumption.',
'A replicated2² factorial has r=3 observations per cell,SSA24,SSB6,SSAB3,SSE16. Complete ANOVA,Fstatistics and df under the normal equalvariance model.',
'N12,totaldf11. Eachfactor/interactiondf1,error4(r−1)=8. MSE2;FA12,FB3,FAB1.5,eachwithdf1,8. TotalSS49.',
'In an unreplicated2³ factorial,how many total and pure-error df exist? What changes if the three-factor interaction is pooled as error?',
'Eightobs,totaldf7;intercept plus7effects saturates data,pureerrordf0. PoolingABC supplies1model-based errordf only by assuming that interaction is negligible/zero;it is not independently replicated pure error and may bias tests if assumption fails.']
];
