// Individually authored original tasks. Columns: order, lesson, main, reference, transfer, reference.
export default [
[1, 'A formula and its domain jointly specify a function. A rewrite is justified at legal inputs; it cannot enlarge the original domain.',
'For f(x)=(x²−4)/(x²−x−2) and g(x)=(x+2)/(x+1), each on its natural real domain, give both domains, simplify f retaining restrictions, give the exact equality set, and decide function equality with justification.',
'Dom f=R\\{−1, 2}, Dom g=R\\{−1}. Factoring gives (x−2)(x+2)/((x−2)(x+1)); cancel only for x≠2. Equality set R\\{−1, 2}. The functions differ because their domains differ.',
'Compare P(x)=(x³−8)/(x²−4) and Q(x)=(x²+2x+4)/(x+2) on their natural real domains. Give a legal simplification, both domains, equality set and function verdict.',
'P has domain R\\{−2, 2}; Q has domain R\\{−2}. Factor x³−8=(x−2)(x²+2x+4); cancellation is legal only off ±2. Equality set R\\{−2, 2}; the functions are not identical.'],
[2, 'Principal roots are nonnegative. For reduced p/q with q>0, an even q requires nonnegative base; a negative exponent also excludes zero. Real logarithms require positive arguments.',
'Audit √((x−2)²)=x−2, (x−2)^(−2/3), and log((x−2)²)=2log(x−2). State each domain and exactly where each asserted equality holds.',
'The root is |x−2| for all reals and equals x−2 iff x≥2. The reduced negative power is defined for x≠2. The left logarithm is defined off 2; the right requires x>2. Their common-domain identity holds for x>2; generally log((x−2)²)=2log|x−2|.',
'On the real line audit √(a²b²)=ab and log(ab)=log a+log b. Then give the domain of (x+1)^(3/4)/√(2−x).',
'The root is |ab|, agreeing with ab iff ab≥0. log(ab) requires ab>0; the split requires a, b>0. The quotient requires x+1≥0 and 2−x>0, so [−1, 2).'],
[3, 'An equivalent step preserves the entire solution set. Squaring can introduce candidates; dividing by an expression can lose its zero cases.',
'Solve √(x+2)=x by labelling each transformation as equivalence or implication, stating all conditions, and checking candidates. Audit the claim x(x−1)=0 implies x−1=0 by division.',
'The equation requires x≥0. Squaring without that restriction is only forward implication and gives x²−x−2=0, candidates2, −1. Only2 satisfies the original. Division by x loses x=0; product equation has solutions0, 1.',
'A proposed solution of (x−1)/(x−2)=1/(x−2) multiplies by x−2 and reports x=2. Locate and repair the error; contrast multiplication by a known nonzero constant.',
'Original domain excludes2. On that domain multiplication is equivalent and leads to x=2, which violates the retained restriction, so the solution set is empty. Multiplication by a known nonzero constant is unconditionally reversible.'],
[4, 'A rational sign analysis distinguishes numerator zeros from denominator exclusions. An even-multiplicity factor need not change sign.',
'Solve (x−1)(x+2)/(x−3)≥0. Justify all sign intervals and endpoint decisions; explain why unqualified cross multiplication is invalid.',
'Critical points−2, 1, 3; signs−, +, −, + from left to right. Solution [−2, 1]∪(3, ∞). Zeros included; pole excluded. x−3 changes sign.',
'Solve (x−1)²/((x+2)(x−1))≤0 from the original expression, preserving every exclusion.',
'Exclude−2, 1 before cancellation. Remaining sign is (x−1)/(x+2), negative only between−2 and1. The original has no legal zero; answer(−2, 1).'],
[5, 'In f(E), the entire expression E is supplied as input. Transport the input-domain condition through E; distinguish input from output and state which symbols vary.',
'For fixed real θ define Cθ(u)=(u−2θ)/(u+θ), u≠−θ. Audit Cθ(x+h), Cθ(θ), R(θ)=Cθ(2), and Cθ(x²): values, exact domains, symbol roles. Treat h as fixed. Give all sign cases for the last domain.',
'Cθ(x+h)=(x+h−2θ)/(x+h+θ), x≠−θ−h, with θ, h fixed. Cθ(θ)=−1/2 if θ≠0, undefined at0. R(θ)=(2−2θ)/(2+θ), θ≠−2, with θ now variable. Last value (x²−2θ)/(x²+θ): θ>0 all x; θ=0 x≠0; θ<0 exclude ±√(−θ).',
'For fixed s let Ps(r)=√(s−r), r≤s. Define Q(s)=Ps(2s−1). Determine its value and domain, explain the change in role of s, and decide whether replacing placeholder r by z changes Ps.',
'Q(s)=√(1−s), s≤1. s selects a fixed family member before the new definition; it varies in Q. A consistent placeholder renaming, including the domain, leaves each member unchanged.'],
[6, 'An affine iterate is composition, not a power of the output. Separate exceptional multipliers before using a geometric-sum formula.',
'For T(x)=ax+b with fixed real a, b derive T composed n times for positive integer n, including a=1. Classify fixed points.',
'Induction gives a^n x+bΣ(j=0 to n−1)a^j. If a≠1 this is a^n x+b(1−a^n)/(1−a); if a=1 it is x+nb. Fixed point b/(1−a) for a≠1; all reals if a=1, b=0, none if a=1, b≠0.',
'Classify real a, b for which T(T(x))=x for every real x. Determine which of those maps have a unique fixed point.',
'Coefficients give a²=1 and b(a+1)=0. Either a=1, b=0 (identity, all fixed) or a=−1, any b (unique fixed point b/2).'],
[7, 'Negation swaps universal/existential quantifiers and negates the predicate. A converse reverses implication; it needs its own proof.',
'Negate: for every real x there exists real y with y>x and y²<2. Decide the original truth. Test the converse of “n divisible by4 implies n even” over integers.',
'Negation: there exists x such that for every y, y≤x or y²≥2. Original false, e.g.x=2. Converse false at n=2; divisibility by4 is sufficient, not necessary, for evenness.',
'Negate “there exists real M such that every positive integer n satisfies n²≤M”. Test “ab=0 implies a=0” and its converse over reals.',
'Negation: for every M there is positive integer n with n²>M; true. Product implication false at a=1, b=0. Converse a=0⇒ab=0 is true for every b.'],
[8, 'A proof must cover every allowed input. One verified admissible counterexample disproves a universal claim; several successful examples do not prove it.',
'Prove that an integer n with n² odd must be odd, specifying the method. Decide whether the sum of two irrational reals is always irrational.',
'Contrapositive: n=2k implies n²=4k² even. The irrational-sum claim fails for √2 and−√2, whose sum is0.',
'Prove that if a, b are real and a²+b²=0 then a=b=0. Refute “a²=b² implies a=b” and state the correct conclusion.',
'Both squares are nonnegative, so a positive one would force positive sum; hence both vanish. a=1, b=−1 refutes the claim. Factoring gives a=b or a=−b.'],
[9, 'Prove a set identity by tracking membership. Preimages preserve intersections; images can merge distinct source points.',
'For f:R→R, f(x)=x², A=[−2, 0], B=[0, 2], compute f(A∩B), f(A)∩f(B), and f^−1([1, 4]). Prove the general preimage-intersection identity.',
'The first is{0}, second[0, 4], preimage[−2, −1]∪[1, 2]. x belongs to f^−1(U∩V) iff f(x) belongs to both U, V, iff x belongs to both preimages.',
'For any map f:X→Y prove f^−1(Y\\U)=X\\f^−1(U). Give an example where f(A\\B) differs from f(A)\\f(B).',
'Membership is f(x)∉U on each side. For x², A={−1, 1}, B={1}: f(A\\B)={1}, whereas f(A)\\f(B) is empty.'],
[10, 'An equivalence relation needs reflexivity, symmetry and transitivity on the declared set. Its equivalence classes partition that set.',
'On{0, 1, 2, 3, 4, 5}, define a~b iff a−b is divisible by3. Prove equivalence and list all distinct classes. Is aRb iff a≤b an equivalence relation?',
'Differences0, sign reversal and addition establish the three properties. Classes{0, 3}, {1, 4}, {2, 5}. ≤ is not symmetric (0≤1 but1≰0).',
'On R define x~y iff x²=y². Verify equivalence and describe every class, treating zero separately.',
'Equality of squares gives reflexivity, symmetry, transitivity. Class of nonzero x is{x, −x}; class of0 is{0}.'],
[11, 'Injectivity compares inputs; surjectivity depends on the codomain. An inverse as a two-sided map exists exactly for a bijection.',
'Classify f:R→[0, ∞), f(x)=x² as injective/surjective. Restrict its domain to make a bijection and verify both inverse identities.',
'Not injective by ±1; surjective since √y is a preimage. On[0, ∞) inverse√y gives both compositions identity. A negative-half-line restriction also works with−√y.',
'For h:R\\{1}→R\\{1}, h(x)=(x+1)/(x−1), prove or refute bijectivity and construct its inverse with domain checks.',
'y=1 impossible; solving gives x=(y+1)/(y−1), legal whenever y≠1 and never1. Unique preimage, hence bijective and self-inverse.'],
[12, 'The remainder on division by x−c is P(c). Vieta relates symmetric root expressions to coefficients without requiring explicit roots.',
'Let P(x)=x³−3x²+kx+3 and suppose−1 is a root. Find k, the remaining roots, their sum and product, and the remainder on division by x−2.',
'P(−1)=−1−3−k+3=−1−k, so k=−1. P=(x+1)(x²−4x+3)=(x+1)(x−1)(x−3). Remaining sum4 product3. P(2)=−3.',
'If α, β are roots of x²−5x+3, determine α²+β² and 1/α+1/β, justifying the reciprocals.',
'α+β=5, αβ=3≠0. Squares sum25−6=19; reciprocal sum5/3.'],
[13, 'A nonzero polynomial of degree d has at most d distinct roots. Multiplicity requires divisibility by a power, not just several observations.',
'Find every k for which x²−2kx+1 has a repeated real root, without a graph. If degree≤3 polynomials agree at four distinct points, prove they are identical.',
'A repeated monic quadratic is(x−r)², giving r=k and k²=1. Cases k=±1. The difference polynomial has four roots but degree≤3, so is zero.',
'Find a, b such that x³+ax+b is divisible by (x−2)² by coefficient comparison. Can agreement at only three distinct points certify degree≤3 polynomial equality?',
'Write (x−2)²(x+c); x² coefficient forces c=4, then a=−12, b=16. Three points insufficient: zero polynomial and product of their three linear factors agree there.'],
[14, 'Index finite sums carefully. A geometric sum formula with denominator1−r needs a separate r=1 case. Harmonic progression means reciprocals form an AP and are defined.',
'An AP has u3=7, u8=22. Find its first term, difference and first n-term sum. Derive Σ(k=0 to n−1)ar^k, including r=1 and a=0. If nonzero p, q, r form an HP, express q in terms of p, r with all conditions.',
'd=3, u1=1; sum n(3n−1)/2. GP sum a(1−r^n)/(1−r) for r≠1, otherwise na; zero a gives0. 2/q=1/p+1/r yields q=2pr/(p+r), requiring p, r, p+r≠0.',
'For u_k=5+2k, k=0, ..., n−1, compute the sum. Evaluate Σ(k=2 to n)3·2^k for n≥2 and explain the indexing.',
'AP sum5n+n(n−1)=n²+4n. Geometric sum3(2^(n+1)−4), with n−1 terms starting at12.'],
[15, 'Finite identities can be established before taking limits. Infinite sums require convergence; telescoping also requires the remaining boundary term to converge.',
'Derive a finite formula for Σ(k=1 to n)kr^k, including r=1, then determine its infinite sum and convergence range for real r. Do not differentiate an infinite series.',
'Subtract r times the finite sum: formula r[1−(n+1)r^n+nr^(n+1)]/(1−r)² if r≠1; n(n+1)/2 if r=1. For |r|<1, n|r|^n→0 (eventual term ratio below some q<1), giving r/(1−r)². For |r|≥1 terms do not tend to0.',
'Evaluate Σ(k=1 to n)1/[k(k+1)] and its infinite limit. Contrast with Σ(k=1 to ∞)(−1)^k.',
'1/[k(k+1)]=1/k−1/(k+1), so sum1−1/(n+1), limit1. Alternating unit terms do not approach0 and partial sums oscillate, so no ordinary convergence.'],
[16, 'Sharp inequalities include equality conditions. Positivity matters for reciprocal means, and Cauchy equality means proportional vectors.',
'For positive a, b prove (a+b)(1/a+1/b)≥4 and identify equality. Derive the AM≥GM≥HM chain for two positive numbers.',
'Product−4=(a−b)²/(ab)≥0. AM≥GM from(√a−√b)²≥0; GM≥HM is equivalent to a+b≥2√ab. All equalities iff a=b.',
'For real x, y, z with x+y+z=6 prove x²+y²+z²≥12 and find every equality case. Does the product inequality above hold for arbitrary nonzero a, b?',
'Cauchy:36≤3(x²+y²+z²); equality x=y=z=2. No: a=1, b=−1 gives product0<4.'],
[17, 'Convexity means f(tx+(1−t)y)≤tf(x)+(1−t)f(y) for t∈[0, 1]. Use the supplied definition, rather than an unearned derivative criterion.',
'Using that definition prove x↦x² is convex on R, including equality for 0<t<1. Decide whether x↦−x² is convex.',
'The right side minus left is t(1−t)(x−y)²≥0; interior equality iff x=y. Negative square fails at x=−1, y=1, t=1/2:0≤−1 is false.',
'Prove |tx+(1−t)y|≤t|x|+(1−t)|y| and determine equality when0<t<1. Use it to bound |(a+b+c)/3|.',
'Triangle inequality yields convexity; equality iff x, y have same weak sign, xy≥0. Repeated triangle inequality gives |(a+b+c)/3|≤(|a|+|b|+|c|)/3.'],
[18, 'Monotone and bounded sequences converge; boundedness alone does not imply convergence. Subsequence behavior can refute convergence.',
'Classify a_n=n/(n+1) for n≥1 as monotone and bounded, and establish its limit. Give a bounded nonconvergent sequence and justify nonconvergence.',
'a_(n+1)−a_n=1/((n+1)(n+2))>0; 1/2≤a_n<1; |a_n−1|=1/(n+1)→0. (−1)^n has subsequences±1, so no limit.',
'Is every convergent sequence monotone? Is every increasing sequence bounded? Supply rigorous counterexamples or proofs.',
'No: (−1)^n/n→0 but is not monotone. No: a_n=n is increasing and unbounded.'],
[19, 'To identify a recurrence limit first justify convergence, then pass through a continuous expression. A fixed-point equation alone does not prove convergence.',
'Let a1=1 and a_(n+1)=√(2+a_n). Prove convergence and find its limit.',
'Induction gives1≤a_n≤2; on[1, 2], 2+x≥x², hence a_(n+1)≥a_n. Monotone bounded convergence gives L∈[1, 2], L²=2+L, so L=2.',
'If a_(2n)→L and a_(2n−1)→L, prove a_n→L. Explain what changes if the limits differ.',
'Given ε choose thresholds for both subsequences and take n above twice their maximum. Every term then lies within ε of L. Different subsequential limits contradict uniqueness of a convergent sequence limit.'],
[20, 'A functional constraint is required at every allowed argument. Substitute compatible arguments and test exceptional values; a guessed example is not a classification.',
'If f:R→R satisfies f(x+1)=f(x)+2 for all x, determine f(x+n) for every integer n. Can f be1-periodic or bounded on R?',
'Iteration in both directions gives f(x+n)=f(x)+2n. It cannot be1-periodic or bounded, since values on any integer translate diverge.',
'Suppose f(f(x))=x for all real x. Prove f is bijective. Does this force f to be the identity? Give a nonidentity example.',
'If f(a)=f(b), applying f yields a=b. Every y=f(f(y)) has a preimage. f(x)=−x is a nonidentity involution.'],
[21, 'Radians measure arc length divided by radius. Signs come from the quadrant; inverse-trig principal values do not replace all possible angles.',
'If θ∈(π/2, π) and sinθ=3/5, determine cosθ, tanθ and sin2θ. A triangle has sides3, 4 with included angleπ/3; find the opposite side using the cosine rule and state the sine rule.',
'cosθ=−4/5, tanθ=−3/4, sin2θ=−24/25. Opposite side√(9+16−24·1/2)=√13. Sine rule a/sin A=b/sin B=c/sin C=2R.',
'A circle of radius3 has an arc subtending2 radians. Find its length. Derive cos(α−β) for α=π/3, β=π/6 and explain the quadrant sign.',
'Arc length6. Cosine difference cosαcosβ+sinαsinβ=√3/2, positive since differenceπ/6 lies in quadrantI.'],
[22, 'Keep every periodic branch and reject inputs where the original expression is undefined. Squared identities can hide sign information.',
'Solve2sin²x−sinx−1=0 on[0, 2π). Then solve tanx=1 on R with its legal domain.',
'Sine values1, −1/2 give x=π/2, 7π/6, 11π/6. tan equation x=π/4+kπ, k∈Z; polesπ/2+kπ excluded from domain.',
'Solve cos2x=cosx on[0, 2π). Simplify √(sin²x) and state exactly when it equals sinx.',
'2c²−c−1=0 gives c=1 or−1/2, hence0, 2π/3, 4π/3. Root=|sinx|; equality iff sinx≥0.'],
[23, 'For z≠0, polar form uses positive modulus and arguments modulo2π. The zero complex number has no defined argument.',
'Write1−i√3 in polar form, compute its cube and reciprocal, and verify the reciprocal in Cartesian form.',
'Modulus2, arg−π/3 mod2π. Cube8e^(−iπ)=−8. Reciprocal (1+i√3)/4, modulus1/2, argπ/3.',
'For z=−1+i compute conjugate, modulus, a principal argument in(−π, π], and z/conjugate(z). Explain the z=0 exception.',
'Conjugate−1−i, modulus√2, arg3π/4; ratio−i. At0 reciprocal and ratio undefined and argument unspecified.'],
[24, 'A nonzero complex w has n distinct nth roots: modulus |w|^(1/n), arguments(arg w+2kπ)/n. A modulus equation may describe a locus, not finitely many roots.',
'Find every solution of z³=8 and justify completeness. Describe the locus |z−1|=|z+1|.',
'Roots2, −1+i√3, −1−i√3; three distinct roots exhaust a cubic. Writing z=x+iy and squaring distances yields x=0, the imaginary axis.',
'Solve z⁴=−16 and separately z⁴=0. Describe z=conjugate(z).',
'Nonzero roots2exp(i(π/4+kπ/2)), k=0, 1, 2, 3. Zero equation has only0 (multiplicity4). Conjugate equation describes all real z.'],
[25, 'Convert geometry into equations with an explicit coordinate system. Vertical lines require a form that does not divide by a zero horizontal displacement.',
'Find the line through(1, 2), (1, −3). Find the centre and radius of x²+y²−4x+6y−12=0, then its distance from the origin.',
'Line x=1. Completing squares gives(x−2)²+(y+3)²=25; centre(2, −3), radius5, distance√13.',
'Find the circle with diameter endpoints(−1, 0), (3, 4). Determine whether(1, 0) lies inside, on, or outside it.',
'Centre(1, 2), radius√8; equation(x−1)²+(y−2)²=8. Point distance²4<8, hence inside.'],
[26, 'Tangency can be checked by centre-to-line distance or a repeated intersection root. A parametrisation must state any point it misses.',
'For x²+y²=5 and y=mx+3, find all real slopes m giving tangency and the tangent points.',
'Distance3/√(m²+1)=√5 gives m=±2/√5. Foot from origin on mx−y+3=0 is(−3m/(1+m²), 3/(1+m²))=(−5m/3, 5/3).',
'Intersect y=t(x−1) with x²+y²=1. Parametrise the second intersection and identify the omitted point for finite real t. Explain why rational t gives rational coordinates.',
'Factoring after substitution gives second point((t²−1)/(t²+1), −2t/(t²+1)). All circle points except(1, 0) occur for finite t; both coordinates rational for rational t.']
];
